// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file bibliophage/v1alpha3/chat.proto (package bibliophage.v1alpha3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChatRequest, ChatResponseChunk } from "./chat_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definition with server-streaming RPC for chat
 *
 * @generated from service bibliophage.v1alpha3.ChatService
 */
export const ChatService = {
  typeName: "bibliophage.v1alpha3.ChatService",
  methods: {
    /**
     * Stream chat responses token-by-token from the LLM
     *
     * @generated from rpc bibliophage.v1alpha3.ChatService.StreamChat
     */
    streamChat: {
      name: "StreamChat",
      I: ChatRequest,
      O: ChatResponseChunk,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

