// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file bibliophage/v1alpha3/document.proto (package bibliophage.v1alpha3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { SortOrder, Tag, TagFilter } from "./common_pb.js";

/**
 * Enums for strict classification of data
 * TODO: A single Document may contain multiple types of information
 * this should probably be an array of applicable types in the future
 * that raises the question whether we need different levels of "authoritativeness"
 * for the different facets of a document
 *
 * @generated from enum bibliophage.v1alpha3.DocumentType
 */
export enum DocumentType {
  /**
   * Default/unknown
   *
   * @generated from enum value: DOCUMENT_TYPE_UNSPECIFIED = 0;
   */
  DOCUMENT_TYPE_UNSPECIFIED = 0,

  /**
   * General notes, least specific
   *
   * @generated from enum value: NOTE = 1;
   */
  NOTE = 1,

  /**
   * Authoritative lore/world information
   *
   * @generated from enum value: LORE_FRAGMENT = 2;
   */
  LORE_FRAGMENT = 2,

  /**
   * PCs, NPCs, historical figures
   *
   * @generated from enum value: CHARACTER = 3;
   */
  CHARACTER = 3,

  /**
   * Places, regions, buildings
   *
   * @generated from enum value: LOCATION = 4;
   */
  LOCATION = 4,

  /**
   * Possessions, items, artifacts
   *
   * @generated from enum value: OBJECT = 5;
   */
  OBJECT = 5,

  /**
   * Quests, missions, plot hooks
   *
   * @generated from enum value: QUEST = 6;
   */
  QUEST = 6,

  /**
   * Session summaries, game logs
   *
   * @generated from enum value: SESSION_LOG = 7;
   */
  SESSION_LOG = 7,

  /**
   * Core rulebook (typically from PDF)
   *
   * @generated from enum value: RULEBOOK = 8;
   */
  RULEBOOK = 8,

  /**
   * Supplement/expansion (typically from PDF)
   *
   * @generated from enum value: EXPANSION = 9;
   */
  EXPANSION = 9,

  /**
   * Adventure module (typically from PDF)
   *
   * @generated from enum value: ADVENTURE = 10;
   */
  ADVENTURE = 10,

  /**
   * Monster/creature compendium (typically from PDF)
   *
   * @generated from enum value: BESTIARY = 11;
   */
  BESTIARY = 11,
}
// Retrieve enum metadata with: proto3.getEnumType(DocumentType)
proto3.util.setEnumType(DocumentType, "bibliophage.v1alpha3.DocumentType", [
  { no: 0, name: "DOCUMENT_TYPE_UNSPECIFIED" },
  { no: 1, name: "NOTE" },
  { no: 2, name: "LORE_FRAGMENT" },
  { no: 3, name: "CHARACTER" },
  { no: 4, name: "LOCATION" },
  { no: 5, name: "OBJECT" },
  { no: 6, name: "QUEST" },
  { no: 7, name: "SESSION_LOG" },
  { no: 8, name: "RULEBOOK" },
  { no: 9, name: "EXPANSION" },
  { no: 10, name: "ADVENTURE" },
  { no: 11, name: "BESTIARY" },
]);

/**
 * SourceType categorizes who created  a document or where a document came from
 * Used to weight authority when constructing LLM context
 *
 * @generated from enum bibliophage.v1alpha3.SourceType
 */
export enum SourceType {
  /**
   * Default/unknown
   *
   * @generated from enum value: SOURCE_TYPE_UNSPECIFIED = 0;
   */
  SOURCE_TYPE_UNSPECIFIED = 0,

  /**
   * Official published rules (highest authority)
   *
   * @generated from enum value: CORE = 1;
   */
  CORE = 1,

  /**
   * Official expansions/supplements
   *
   * @generated from enum value: SUPPLEMENT = 2;
   */
  SUPPLEMENT = 2,

  /**
   * Game master's notes and preparations
   *
   * @generated from enum value: GM_NOTES = 3;
   */
  GM_NOTES = 3,

  /**
   * Player character journals/notes
   *
   * @generated from enum value: PLAYER_NOTES = 4;
   */
  PLAYER_NOTES = 4,

  /**
   * Actual play session records
   *
   * @generated from enum value: SESSION_LOG_RECORD = 5;
   */
  SESSION_LOG_RECORD = 5,

  /**
   * LLM-generated content
   *
   * @generated from enum value: GENERATED = 6;
   */
  GENERATED = 6,

  /**
   * Community/fan-created content
   *
   * @generated from enum value: COMMUNITY = 7;
   */
  COMMUNITY = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(SourceType)
proto3.util.setEnumType(SourceType, "bibliophage.v1alpha3.SourceType", [
  { no: 0, name: "SOURCE_TYPE_UNSPECIFIED" },
  { no: 1, name: "CORE" },
  { no: 2, name: "SUPPLEMENT" },
  { no: 3, name: "GM_NOTES" },
  { no: 4, name: "PLAYER_NOTES" },
  { no: 5, name: "SESSION_LOG_RECORD" },
  { no: 6, name: "GENERATED" },
  { no: 7, name: "COMMUNITY" },
]);

/**
 * PDF-specific metadata for documents sourced from PDFs
 *
 * @generated from message bibliophage.v1alpha3.PdfData
 */
export class PdfData extends Message<PdfData> {
  /**
   * Number of batches processed by Docling
   *
   * @generated from field: int32 loading_batch_count = 1;
   */
  loadingBatchCount = 0;

  /**
   * Number of text chunks created for vector embeddings
   *
   * @generated from field: int32 vector_chunk_count = 2;
   */
  vectorChunkCount = 0;

  /**
   * Number of pages in the source material
   *
   * @generated from field: int32 page_count = 3;
   */
  pageCount = 0;

  constructor(data?: PartialMessage<PdfData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.PdfData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "loading_batch_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "vector_chunk_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "page_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PdfData {
    return new PdfData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PdfData {
    return new PdfData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PdfData {
    return new PdfData().fromJsonString(jsonString, options);
  }

  static equals(a: PdfData | PlainMessage<PdfData> | undefined, b: PdfData | PlainMessage<PdfData> | undefined): boolean {
    return proto3.util.equals(PdfData, a, b);
  }
}

/**
 * Metadata for file-based content (PDFs, scanned books, etc.)
 * Populated when DocumentType indicates file-based content
 *
 * @generated from message bibliophage.v1alpha3.Metadata
 */
export class Metadata extends Message<Metadata> {
  /**
   * File size in bytes
   *
   * @generated from field: int64 file_size = 1;
   */
  fileSize = protoInt64.zero;

  /**
   * Publication type (e.g., "Core Rulebook", "Adventure", "Supplement")
   *
   * @generated from field: optional string publication_type = 2;
   */
  publicationType?: string;

  /**
   * PDF-specific data (only populated for PDF-sourced documents)
   *
   * @generated from field: optional bibliophage.v1alpha3.PdfData pdf = 3;
   */
  pdf?: PdfData;

  constructor(data?: PartialMessage<Metadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.Metadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "file_size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "publication_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "pdf", kind: "message", T: PdfData, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Metadata {
    return new Metadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Metadata {
    return new Metadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Metadata {
    return new Metadata().fromJsonString(jsonString, options);
  }

  static equals(a: Metadata | PlainMessage<Metadata> | undefined, b: Metadata | PlainMessage<Metadata> | undefined): boolean {
    return proto3.util.equals(Metadata, a, b);
  }
}

/**
 * Document represents any content in the system (user-created or loaded from files)
 *
 * @generated from message bibliophage.v1alpha3.Document
 */
export class Document extends Message<Document> {
  /**
   * Unique identifier for this document (assigned by the system)
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Human-readable name (e.g., "My Campaign Notes", "Player's Handbook")
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * Source type for LLM context weighting
   *
   * @generated from field: bibliophage.v1alpha3.SourceType source_type = 3;
   */
  sourceType = SourceType.SOURCE_TYPE_UNSPECIFIED;

  /**
   * Metadata for file-based content (populated when type indicates file-based content)
   *
   * @generated from field: optional bibliophage.v1alpha3.Metadata metadata = 4;
   */
  metadata?: Metadata;

  /**
   * Raw text content of the document (markdown formatted for PDFs, user notes should be treated as plain text)
   *
   * @generated from field: string content = 5;
   */
  content = "";

  /**
   * Type of document (categorization)
   *
   * @generated from field: bibliophage.v1alpha3.DocumentType type = 6;
   */
  type = DocumentType.DOCUMENT_TYPE_UNSPECIFIED;

  /**
   * Which RPG system(s) this document belongs to
   * Examples: ["Call of Cthulhu"], ["D&D 3.5e", "Pathfinder 1e"], ["Generic"]
   * Must contain at least one value
   *
   * @generated from field: repeated string systems = 7;
   */
  systems: string[] = [];

  /**
   * When this document was created
   *
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * When this document was last updated
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp;

  /**
   * Structured tags for organization (name + multiple values)
   *
   * @generated from field: repeated bibliophage.v1alpha3.Tag tags = 10;
   */
  tags: Tag[] = [];

  /**
   * Character count
   *
   * @generated from field: int32 character_count = 11;
   */
  characterCount = 0;

  constructor(data?: PartialMessage<Document>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.Document";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "source_type", kind: "enum", T: proto3.getEnumType(SourceType) },
    { no: 4, name: "metadata", kind: "message", T: Metadata, opt: true },
    { no: 5, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "type", kind: "enum", T: proto3.getEnumType(DocumentType) },
    { no: 7, name: "systems", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 8, name: "created_at", kind: "message", T: Timestamp },
    { no: 9, name: "updated_at", kind: "message", T: Timestamp },
    { no: 10, name: "tags", kind: "message", T: Tag, repeated: true },
    { no: 11, name: "character_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Document {
    return new Document().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Document {
    return new Document().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Document {
    return new Document().fromJsonString(jsonString, options);
  }

  static equals(a: Document | PlainMessage<Document> | undefined, b: Document | PlainMessage<Document> | undefined): boolean {
    return proto3.util.equals(Document, a, b);
  }
}

/**
 * DocumentListItem represents a document in list/search results
 * Contains metadata and a content snippet, but not the full content
 * This enforces bandwidth efficiency - clients cannot request full content in searches
 *
 * @generated from message bibliophage.v1alpha3.DocumentListItem
 */
export class DocumentListItem extends Message<DocumentListItem> {
  /**
   * Unique identifier for this document
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Human-readable name
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * Source authority for LLM context weighting
   *
   * @generated from field: bibliophage.v1alpha3.SourceType source_type = 3;
   */
  sourceType = SourceType.SOURCE_TYPE_UNSPECIFIED;

  /**
   * Metadata for file-based content
   *
   * @generated from field: optional bibliophage.v1alpha3.Metadata metadata = 4;
   */
  metadata?: Metadata;

  /**
   * Short excerpt from the content (max ~200 characters)
   * May be empty if the document has no content
   * Use GetDocument RPC to retrieve full content
   *
   * @generated from field: string content_snippet = 5;
   */
  contentSnippet = "";

  /**
   * Type of document
   *
   * @generated from field: bibliophage.v1alpha3.DocumentType type = 6;
   */
  type = DocumentType.DOCUMENT_TYPE_UNSPECIFIED;

  /**
   * Which RPG system(s) this document belongs to
   *
   * @generated from field: repeated string systems = 7;
   */
  systems: string[] = [];

  /**
   * When this document was created
   *
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * When this document was last updated
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp;

  /**
   * Structured tags for organization
   *
   * @generated from field: repeated bibliophage.v1alpha3.Tag tags = 10;
   */
  tags: Tag[] = [];

  /**
   * Character count of full document (not the snippet)
   *
   * @generated from field: int32 character_count = 11;
   */
  characterCount = 0;

  constructor(data?: PartialMessage<DocumentListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DocumentListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "source_type", kind: "enum", T: proto3.getEnumType(SourceType) },
    { no: 4, name: "metadata", kind: "message", T: Metadata, opt: true },
    { no: 5, name: "content_snippet", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "type", kind: "enum", T: proto3.getEnumType(DocumentType) },
    { no: 7, name: "systems", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 8, name: "created_at", kind: "message", T: Timestamp },
    { no: 9, name: "updated_at", kind: "message", T: Timestamp },
    { no: 10, name: "tags", kind: "message", T: Tag, repeated: true },
    { no: 11, name: "character_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DocumentListItem {
    return new DocumentListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DocumentListItem {
    return new DocumentListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DocumentListItem {
    return new DocumentListItem().fromJsonString(jsonString, options);
  }

  static equals(a: DocumentListItem | PlainMessage<DocumentListItem> | undefined, b: DocumentListItem | PlainMessage<DocumentListItem> | undefined): boolean {
    return proto3.util.equals(DocumentListItem, a, b);
  }
}

/**
 * StoreDocumentRequest - Create a new document
 *
 * @generated from message bibliophage.v1alpha3.StoreDocumentRequest
 */
export class StoreDocumentRequest extends Message<StoreDocumentRequest> {
  /**
   * The document to store (ID will be assigned by server)
   *
   * @generated from field: bibliophage.v1alpha3.Document document = 1;
   */
  document?: Document;

  constructor(data?: PartialMessage<StoreDocumentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.StoreDocumentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "document", kind: "message", T: Document },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StoreDocumentRequest {
    return new StoreDocumentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StoreDocumentRequest {
    return new StoreDocumentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StoreDocumentRequest {
    return new StoreDocumentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StoreDocumentRequest | PlainMessage<StoreDocumentRequest> | undefined, b: StoreDocumentRequest | PlainMessage<StoreDocumentRequest> | undefined): boolean {
    return proto3.util.equals(StoreDocumentRequest, a, b);
  }
}

/**
 * StoreDocumentResponse - Result of storing a document
 *
 * @generated from message bibliophage.v1alpha3.StoreDocumentResponse
 */
export class StoreDocumentResponse extends Message<StoreDocumentResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The stored document with assigned ID
   *
   * @generated from field: bibliophage.v1alpha3.Document document = 3;
   */
  document?: Document;

  constructor(data?: PartialMessage<StoreDocumentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.StoreDocumentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "document", kind: "message", T: Document },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StoreDocumentResponse {
    return new StoreDocumentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StoreDocumentResponse {
    return new StoreDocumentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StoreDocumentResponse {
    return new StoreDocumentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StoreDocumentResponse | PlainMessage<StoreDocumentResponse> | undefined, b: StoreDocumentResponse | PlainMessage<StoreDocumentResponse> | undefined): boolean {
    return proto3.util.equals(StoreDocumentResponse, a, b);
  }
}

/**
 * GetDocumentRequest - Retrieve a specific document by ID
 *
 * @generated from message bibliophage.v1alpha3.GetDocumentRequest
 */
export class GetDocumentRequest extends Message<GetDocumentRequest> {
  /**
   * The unique ID of the document to retrieve
   *
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetDocumentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.GetDocumentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetDocumentRequest {
    return new GetDocumentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetDocumentRequest {
    return new GetDocumentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetDocumentRequest {
    return new GetDocumentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetDocumentRequest | PlainMessage<GetDocumentRequest> | undefined, b: GetDocumentRequest | PlainMessage<GetDocumentRequest> | undefined): boolean {
    return proto3.util.equals(GetDocumentRequest, a, b);
  }
}

/**
 * GetDocumentResponse - Result of getting a document
 *
 * @generated from message bibliophage.v1alpha3.GetDocumentResponse
 */
export class GetDocumentResponse extends Message<GetDocumentResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The requested document (null if not found)
   *
   * @generated from field: optional bibliophage.v1alpha3.Document document = 3;
   */
  document?: Document;

  constructor(data?: PartialMessage<GetDocumentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.GetDocumentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "document", kind: "message", T: Document, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetDocumentResponse {
    return new GetDocumentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetDocumentResponse {
    return new GetDocumentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetDocumentResponse {
    return new GetDocumentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetDocumentResponse | PlainMessage<GetDocumentResponse> | undefined, b: GetDocumentResponse | PlainMessage<GetDocumentResponse> | undefined): boolean {
    return proto3.util.equals(GetDocumentResponse, a, b);
  }
}

/**
 * UpdateDocumentRequest - Update an existing document
 *
 * @generated from message bibliophage.v1alpha3.UpdateDocumentRequest
 */
export class UpdateDocumentRequest extends Message<UpdateDocumentRequest> {
  /**
   * The document to update (must include ID)
   *
   * @generated from field: bibliophage.v1alpha3.Document document = 1;
   */
  document?: Document;

  constructor(data?: PartialMessage<UpdateDocumentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.UpdateDocumentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "document", kind: "message", T: Document },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateDocumentRequest {
    return new UpdateDocumentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateDocumentRequest {
    return new UpdateDocumentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateDocumentRequest {
    return new UpdateDocumentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateDocumentRequest | PlainMessage<UpdateDocumentRequest> | undefined, b: UpdateDocumentRequest | PlainMessage<UpdateDocumentRequest> | undefined): boolean {
    return proto3.util.equals(UpdateDocumentRequest, a, b);
  }
}

/**
 * UpdateDocumentResponse - Result of updating a document
 *
 * @generated from message bibliophage.v1alpha3.UpdateDocumentResponse
 */
export class UpdateDocumentResponse extends Message<UpdateDocumentResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The updated document
   *
   * @generated from field: bibliophage.v1alpha3.Document document = 3;
   */
  document?: Document;

  constructor(data?: PartialMessage<UpdateDocumentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.UpdateDocumentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "document", kind: "message", T: Document },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateDocumentResponse {
    return new UpdateDocumentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateDocumentResponse {
    return new UpdateDocumentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateDocumentResponse {
    return new UpdateDocumentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateDocumentResponse | PlainMessage<UpdateDocumentResponse> | undefined, b: UpdateDocumentResponse | PlainMessage<UpdateDocumentResponse> | undefined): boolean {
    return proto3.util.equals(UpdateDocumentResponse, a, b);
  }
}

/**
 * DocumentFilter - Reusable filter criteria for document searches
 * This can be used across different search endpoints and services
 *
 * @generated from message bibliophage.v1alpha3.DocumentFilter
 */
export class DocumentFilter extends Message<DocumentFilter> {
  /**
   * Search by name (partial match, case-insensitive)
   *
   * @generated from field: optional string name_query = 1;
   */
  nameQuery?: string;

  /**
   * Search by content (partial match, case-insensitive)
   *
   * @generated from field: optional string content_query = 2;
   */
  contentQuery?: string;

  /**
   * Filter by type (exact match)
   *
   * @generated from field: optional bibliophage.v1alpha3.DocumentType type_filter = 3;
   */
  typeFilter?: DocumentType;

  /**
   * Filter by tags (documents must match ALL specified tag filters)
   * Example: [{"name": "genre", "value": "fantasy"}, {"name": "tone", "value": "dark"}]
   * would match documents that have both genre=fantasy AND tone=dark
   *
   * @generated from field: repeated bibliophage.v1alpha3.TagFilter tag_filters = 4;
   */
  tagFilters: TagFilter[] = [];

  /**
   * Filter by systems (returns documents where systems contains ANY of these values)
   * Example: ["Call of Cthulhu", "Pathfinder 1e", "Generic"] returns CoC + Pathfinder + generic docs
   *
   * @generated from field: repeated string system_filters = 5;
   */
  systemFilters: string[] = [];

  constructor(data?: PartialMessage<DocumentFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DocumentFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name_query", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "content_query", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "type_filter", kind: "enum", T: proto3.getEnumType(DocumentType), opt: true },
    { no: 4, name: "tag_filters", kind: "message", T: TagFilter, repeated: true },
    { no: 5, name: "system_filters", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DocumentFilter {
    return new DocumentFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DocumentFilter {
    return new DocumentFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DocumentFilter {
    return new DocumentFilter().fromJsonString(jsonString, options);
  }

  static equals(a: DocumentFilter | PlainMessage<DocumentFilter> | undefined, b: DocumentFilter | PlainMessage<DocumentFilter> | undefined): boolean {
    return proto3.util.equals(DocumentFilter, a, b);
  }
}

/**
 * SearchDocumentsRequest - Search for documents by various criteria
 *
 * @generated from message bibliophage.v1alpha3.SearchDocumentsRequest
 */
export class SearchDocumentsRequest extends Message<SearchDocumentsRequest> {
  /**
   * Filter criteria (all fields are optional)
   *
   * @generated from field: optional bibliophage.v1alpha3.DocumentFilter filter = 1;
   */
  filter?: DocumentFilter;

  /**
   * Pagination (optional, server applies defaults if not specified)
   *
   * Max results to return (default: 50)
   *
   * @generated from field: optional int32 page_size = 2;
   */
  pageSize?: number;

  /**
   * Which page of results (0-indexed, default: 0)
   *
   * @generated from field: optional int32 page_number = 3;
   */
  pageNumber?: number;

  /**
   * Sorting
   *
   * @generated from field: optional bibliophage.v1alpha3.SortOrder sort_order = 4;
   */
  sortOrder?: SortOrder;

  constructor(data?: PartialMessage<SearchDocumentsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.SearchDocumentsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "filter", kind: "message", T: DocumentFilter, opt: true },
    { no: 2, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 3, name: "page_number", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 4, name: "sort_order", kind: "enum", T: proto3.getEnumType(SortOrder), opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchDocumentsRequest {
    return new SearchDocumentsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchDocumentsRequest {
    return new SearchDocumentsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchDocumentsRequest {
    return new SearchDocumentsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SearchDocumentsRequest | PlainMessage<SearchDocumentsRequest> | undefined, b: SearchDocumentsRequest | PlainMessage<SearchDocumentsRequest> | undefined): boolean {
    return proto3.util.equals(SearchDocumentsRequest, a, b);
  }
}

/**
 * SearchDocumentsResponse - Results of document search
 *
 * @generated from message bibliophage.v1alpha3.SearchDocumentsResponse
 */
export class SearchDocumentsResponse extends Message<SearchDocumentsResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * Array of matching document summaries (with snippets, not full content)
   * To retrieve full content, use GetDocument RPC with the document ID
   *
   * @generated from field: repeated bibliophage.v1alpha3.DocumentListItem matches = 3;
   */
  matches: DocumentListItem[] = [];

  /**
   * Total number of results (for pagination)
   *
   * @generated from field: int32 total_count = 4;
   */
  totalCount = 0;

  /**
   * Current page number
   *
   * @generated from field: int32 page_number = 5;
   */
  pageNumber = 0;

  /**
   * Whether there are more pages
   *
   * @generated from field: bool has_more = 6;
   */
  hasMore = false;

  constructor(data?: PartialMessage<SearchDocumentsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.SearchDocumentsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "matches", kind: "message", T: DocumentListItem, repeated: true },
    { no: 4, name: "total_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "page_number", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "has_more", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchDocumentsResponse {
    return new SearchDocumentsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchDocumentsResponse {
    return new SearchDocumentsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchDocumentsResponse {
    return new SearchDocumentsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SearchDocumentsResponse | PlainMessage<SearchDocumentsResponse> | undefined, b: SearchDocumentsResponse | PlainMessage<SearchDocumentsResponse> | undefined): boolean {
    return proto3.util.equals(SearchDocumentsResponse, a, b);
  }
}

/**
 * DeleteDocumentRequest - Delete a document by ID
 *
 * @generated from message bibliophage.v1alpha3.DeleteDocumentRequest
 */
export class DeleteDocumentRequest extends Message<DeleteDocumentRequest> {
  /**
   * The unique ID of the document to delete
   *
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DeleteDocumentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteDocumentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteDocumentRequest {
    return new DeleteDocumentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteDocumentRequest {
    return new DeleteDocumentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteDocumentRequest {
    return new DeleteDocumentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteDocumentRequest | PlainMessage<DeleteDocumentRequest> | undefined, b: DeleteDocumentRequest | PlainMessage<DeleteDocumentRequest> | undefined): boolean {
    return proto3.util.equals(DeleteDocumentRequest, a, b);
  }
}

/**
 * DeleteDocumentResponse - Result of deleting a document
 *
 * @generated from message bibliophage.v1alpha3.DeleteDocumentResponse
 */
export class DeleteDocumentResponse extends Message<DeleteDocumentResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<DeleteDocumentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteDocumentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteDocumentResponse {
    return new DeleteDocumentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteDocumentResponse {
    return new DeleteDocumentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteDocumentResponse {
    return new DeleteDocumentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteDocumentResponse | PlainMessage<DeleteDocumentResponse> | undefined, b: DeleteDocumentResponse | PlainMessage<DeleteDocumentResponse> | undefined): boolean {
    return proto3.util.equals(DeleteDocumentResponse, a, b);
  }
}

