// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file bibliophage/v1alpha3/embedding.proto (package bibliophage.v1alpha3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteEmbeddingsRequest, DeleteEmbeddingsResponse, EmbedDocumentRequest, EmbedDocumentResponse, GetChunkBoundariesRequest, GetChunkBoundariesResponse, ProposeChunksRequest, ProposeChunksResponse, UpdateChunkBoundariesRequest, UpdateChunkBoundariesResponse } from "./embedding_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definitions - the API endpoints
 *
 * @generated from service bibliophage.v1alpha3.EmbeddingService
 */
export const EmbeddingService = {
  typeName: "bibliophage.v1alpha3.EmbeddingService",
  methods: {
    /**
     * @generated from rpc bibliophage.v1alpha3.EmbeddingService.ProposeChunks
     */
    proposeChunks: {
      name: "ProposeChunks",
      I: ProposeChunksRequest,
      O: ProposeChunksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.EmbeddingService.EmbedDocument
     */
    embedDocument: {
      name: "EmbedDocument",
      I: EmbedDocumentRequest,
      O: EmbedDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.EmbeddingService.GetChunkBoundaries
     */
    getChunkBoundaries: {
      name: "GetChunkBoundaries",
      I: GetChunkBoundariesRequest,
      O: GetChunkBoundariesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.EmbeddingService.UpdateChunkBoundaries
     */
    updateChunkBoundaries: {
      name: "UpdateChunkBoundaries",
      I: UpdateChunkBoundariesRequest,
      O: UpdateChunkBoundariesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.EmbeddingService.DeleteEmbeddings
     */
    deleteEmbeddings: {
      name: "DeleteEmbeddings",
      I: DeleteEmbeddingsRequest,
      O: DeleteEmbeddingsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

