// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file bibliophage/v1alpha3/embedding.proto (package bibliophage.v1alpha3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * ChunkingStrategy defines the method used to split document content into chunks
 *
 * @generated from enum bibliophage.v1alpha3.ChunkingStrategy
 */
export enum ChunkingStrategy {
  /**
   * Default/unknown
   *
   * @generated from enum value: CHUNKING_STRATEGY_UNSPECIFIED = 0;
   */
  CHUNKING_STRATEGY_UNSPECIFIED = 0,

  /**
   * RecursiveCharacterTextSplitter with token limits
   *
   * @generated from enum value: TOKEN_BASED = 1;
   */
  TOKEN_BASED = 1,

  /**
   * Split at heading boundaries
   *
   * @generated from enum value: MARKDOWN_STRUCTURE = 2;
   */
  MARKDOWN_STRUCTURE = 2,

  /**
   * Hybrid: respect headings, split if too large
   *
   * @generated from enum value: MARKDOWN_WITH_TOKEN_LIMIT = 3;
   */
  MARKDOWN_WITH_TOKEN_LIMIT = 3,

  /**
   * Split at page markers (<!-- PAGE N -->)
   *
   * @generated from enum value: PDF_PAGE_BASED = 4;
   */
  PDF_PAGE_BASED = 4,

  /**
   * User manually edited chunk boundaries
   *
   * @generated from enum value: USER_DEFINED = 5;
   */
  USER_DEFINED = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(ChunkingStrategy)
proto3.util.setEnumType(ChunkingStrategy, "bibliophage.v1alpha3.ChunkingStrategy", [
  { no: 0, name: "CHUNKING_STRATEGY_UNSPECIFIED" },
  { no: 1, name: "TOKEN_BASED" },
  { no: 2, name: "MARKDOWN_STRUCTURE" },
  { no: 3, name: "MARKDOWN_WITH_TOKEN_LIMIT" },
  { no: 4, name: "PDF_PAGE_BASED" },
  { no: 5, name: "USER_DEFINED" },
]);

/**
 * MarkdownReference represents a position in the document by markdown structure
 *
 * @generated from message bibliophage.v1alpha3.MarkdownReference
 */
export class MarkdownReference extends Message<MarkdownReference> {
  /**
   * Path through headings to reach this chunk
   * Example: ["Chapter 1", "Combat Rules", "Initiative"]
   *
   * @generated from field: repeated string heading_path = 1;
   */
  headingPath: string[] = [];

  /**
   * Heading level where this chunk starts (1 = #, 2 = ##, etc.)
   *
   * @generated from field: int32 start_heading_level = 2;
   */
  startHeadingLevel = 0;

  constructor(data?: PartialMessage<MarkdownReference>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.MarkdownReference";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "heading_path", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "start_heading_level", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarkdownReference {
    return new MarkdownReference().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarkdownReference {
    return new MarkdownReference().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarkdownReference {
    return new MarkdownReference().fromJsonString(jsonString, options);
  }

  static equals(a: MarkdownReference | PlainMessage<MarkdownReference> | undefined, b: MarkdownReference | PlainMessage<MarkdownReference> | undefined): boolean {
    return proto3.util.equals(MarkdownReference, a, b);
  }
}

/**
 * PdfPageReference represents a position in a PDF document
 *
 * @generated from message bibliophage.v1alpha3.PdfPageReference
 */
export class PdfPageReference extends Message<PdfPageReference> {
  /**
   * Starting page number (1-indexed)
   *
   * @generated from field: int32 start_page = 1;
   */
  startPage = 0;

  /**
   * Ending page number (1-indexed, inclusive)
   *
   * @generated from field: int32 end_page = 2;
   */
  endPage = 0;

  constructor(data?: PartialMessage<PdfPageReference>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.PdfPageReference";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "start_page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "end_page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PdfPageReference {
    return new PdfPageReference().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PdfPageReference {
    return new PdfPageReference().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PdfPageReference {
    return new PdfPageReference().fromJsonString(jsonString, options);
  }

  static equals(a: PdfPageReference | PlainMessage<PdfPageReference> | undefined, b: PdfPageReference | PlainMessage<PdfPageReference> | undefined): boolean {
    return proto3.util.equals(PdfPageReference, a, b);
  }
}

/**
 * ChunkBoundary defines a single chunk's position and metadata
 *
 * @generated from message bibliophage.v1alpha3.ChunkBoundary
 */
export class ChunkBoundary extends Message<ChunkBoundary> {
  /**
   * Unique identifier for this chunk (e.g., "doc-uuid:chunk:0")
   *
   * @generated from field: string chunk_id = 1;
   */
  chunkId = "";

  /**
   * Character offset where this chunk starts (0-indexed)
   *
   * @generated from field: int32 char_start = 2;
   */
  charStart = 0;

  /**
   * Character offset where this chunk ends (0-indexed, exclusive)
   *
   * @generated from field: int32 char_end = 3;
   */
  charEnd = 0;

  /**
   * Token offset where this chunk starts (optional, for token-based strategies)
   *
   * @generated from field: optional int32 token_start = 4;
   */
  tokenStart?: number;

  /**
   * Token offset where this chunk ends (optional, for token-based strategies)
   *
   * @generated from field: optional int32 token_end = 5;
   */
  tokenEnd?: number;

  /**
   * Markdown structure reference (optional, for markdown-based strategies)
   *
   * @generated from field: optional bibliophage.v1alpha3.MarkdownReference markdown_ref = 6;
   */
  markdownRef?: MarkdownReference;

  /**
   * PDF page reference (optional, for PDF documents)
   *
   * @generated from field: optional bibliophage.v1alpha3.PdfPageReference pdf_ref = 7;
   */
  pdfRef?: PdfPageReference;

  /**
   * Human-readable description of this chunk (e.g., heading text)
   *
   * @generated from field: string description = 8;
   */
  description = "";

  /**
   * Short preview of chunk content (first ~100 characters)
   * TODO: this is not needed, just overlay the chunk over the respective document
   * We don't want to display chunks separately from the document they come from
   *
   * @generated from field: string preview = 9;
   */
  preview = "";

  constructor(data?: PartialMessage<ChunkBoundary>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.ChunkBoundary";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "chunk_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "char_start", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "char_end", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "token_start", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 5, name: "token_end", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "markdown_ref", kind: "message", T: MarkdownReference, opt: true },
    { no: 7, name: "pdf_ref", kind: "message", T: PdfPageReference, opt: true },
    { no: 8, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "preview", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChunkBoundary {
    return new ChunkBoundary().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChunkBoundary {
    return new ChunkBoundary().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChunkBoundary {
    return new ChunkBoundary().fromJsonString(jsonString, options);
  }

  static equals(a: ChunkBoundary | PlainMessage<ChunkBoundary> | undefined, b: ChunkBoundary | PlainMessage<ChunkBoundary> | undefined): boolean {
    return proto3.util.equals(ChunkBoundary, a, b);
  }
}

/**
 * ChunkingConfig defines parameters for chunk generation
 *
 * @generated from message bibliophage.v1alpha3.ChunkingConfig
 */
export class ChunkingConfig extends Message<ChunkingConfig> {
  /**
   * Strategy to use for chunking
   *
   * @generated from field: bibliophage.v1alpha3.ChunkingStrategy strategy = 1;
   */
  strategy = ChunkingStrategy.CHUNKING_STRATEGY_UNSPECIFIED;

  /**
   * Token-based chunking: chunk size in tokens (default: 512)
   *
   * @generated from field: optional int32 token_chunk_size = 2;
   */
  tokenChunkSize?: number;

  /**
   * Token-based chunking: overlap in tokens (default: 50)
   *
   * @generated from field: optional int32 token_chunk_overlap = 3;
   */
  tokenChunkOverlap?: number;

  /**
   * Markdown-based chunking: maximum heading level to split at (1-6, default: 3)
   * 1 = split only at # headings, 3 = split at #, ##, and ### headings
   *
   * @generated from field: optional int32 max_heading_level = 4;
   */
  maxHeadingLevel?: number;

  /**
   * Version identifier for reproducibility (e.g., "1.0.0")
   *
   * @generated from field: optional string config_version = 5;
   */
  configVersion?: string;

  constructor(data?: PartialMessage<ChunkingConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.ChunkingConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "strategy", kind: "enum", T: proto3.getEnumType(ChunkingStrategy) },
    { no: 2, name: "token_chunk_size", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 3, name: "token_chunk_overlap", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 4, name: "max_heading_level", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 5, name: "config_version", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChunkingConfig {
    return new ChunkingConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChunkingConfig {
    return new ChunkingConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChunkingConfig {
    return new ChunkingConfig().fromJsonString(jsonString, options);
  }

  static equals(a: ChunkingConfig | PlainMessage<ChunkingConfig> | undefined, b: ChunkingConfig | PlainMessage<ChunkingConfig> | undefined): boolean {
    return proto3.util.equals(ChunkingConfig, a, b);
  }
}

/**
 * EmbeddingStatus represents the current embedding state for a document
 *
 * @generated from message bibliophage.v1alpha3.EmbeddingStatus
 */
export class EmbeddingStatus extends Message<EmbeddingStatus> {
  /**
   * Whether this document has been embedded
   *
   * @generated from field: bool is_embedded = 1;
   */
  isEmbedded = false;

  /**
   * Whether embeddings are current (false if content or boundaries changed)
   *
   * @generated from field: bool embeddings_current = 2;
   */
  embeddingsCurrent = false;

  /**
   * When embeddings were last created
   *
   * @generated from field: optional google.protobuf.Timestamp embedded_at = 3;
   */
  embeddedAt?: Timestamp;

  /**
   * Total number of chunks embedded
   *
   * @generated from field: int32 total_chunks = 4;
   */
  totalChunks = 0;

  /**
   * Embedding model used (e.g., "BAAI/bge-large-en-v1.5")
   *
   * @generated from field: optional string embedding_model = 5;
   */
  embeddingModel?: string;

  /**
   * Name of the vector collection in pgvector
   *
   * @generated from field: optional string vector_collection = 6;
   */
  vectorCollection?: string;

  constructor(data?: PartialMessage<EmbeddingStatus>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.EmbeddingStatus";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "is_embedded", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "embeddings_current", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "embedded_at", kind: "message", T: Timestamp, opt: true },
    { no: 4, name: "total_chunks", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "embedding_model", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "vector_collection", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EmbeddingStatus {
    return new EmbeddingStatus().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EmbeddingStatus {
    return new EmbeddingStatus().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EmbeddingStatus {
    return new EmbeddingStatus().fromJsonString(jsonString, options);
  }

  static equals(a: EmbeddingStatus | PlainMessage<EmbeddingStatus> | undefined, b: EmbeddingStatus | PlainMessage<EmbeddingStatus> | undefined): boolean {
    return proto3.util.equals(EmbeddingStatus, a, b);
  }
}

/**
 * ChunkProposal contains proposed chunk boundaries and statistics
 *
 * @generated from message bibliophage.v1alpha3.ChunkProposal
 */
export class ChunkProposal extends Message<ChunkProposal> {
  /**
   * Array of proposed chunk boundaries
   *
   * @generated from field: repeated bibliophage.v1alpha3.ChunkBoundary boundaries = 1;
   */
  boundaries: ChunkBoundary[] = [];

  /**
   * Configuration used to generate these chunks
   *
   * @generated from field: bibliophage.v1alpha3.ChunkingConfig config = 2;
   */
  config?: ChunkingConfig;

  /**
   * Statistics about the proposed chunks
   *
   * @generated from field: bibliophage.v1alpha3.ChunkStatistics statistics = 3;
   */
  statistics?: ChunkStatistics;

  constructor(data?: PartialMessage<ChunkProposal>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.ChunkProposal";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "boundaries", kind: "message", T: ChunkBoundary, repeated: true },
    { no: 2, name: "config", kind: "message", T: ChunkingConfig },
    { no: 3, name: "statistics", kind: "message", T: ChunkStatistics },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChunkProposal {
    return new ChunkProposal().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChunkProposal {
    return new ChunkProposal().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChunkProposal {
    return new ChunkProposal().fromJsonString(jsonString, options);
  }

  static equals(a: ChunkProposal | PlainMessage<ChunkProposal> | undefined, b: ChunkProposal | PlainMessage<ChunkProposal> | undefined): boolean {
    return proto3.util.equals(ChunkProposal, a, b);
  }
}

/**
 * ChunkStatistics provides metrics about a set of chunks
 *
 * @generated from message bibliophage.v1alpha3.ChunkStatistics
 */
export class ChunkStatistics extends Message<ChunkStatistics> {
  /**
   * Total number of chunks
   *
   * @generated from field: int32 total_chunks = 1;
   */
  totalChunks = 0;

  /**
   * Average chunk size in characters
   *
   * @generated from field: int32 avg_chunk_size = 2;
   */
  avgChunkSize = 0;

  /**
   * Minimum chunk size in characters
   *
   * @generated from field: int32 min_chunk_size = 3;
   */
  minChunkSize = 0;

  /**
   * Maximum chunk size in characters
   *
   * @generated from field: int32 max_chunk_size = 4;
   */
  maxChunkSize = 0;

  /**
   * Total content length in characters
   *
   * @generated from field: int32 total_content_length = 5;
   */
  totalContentLength = 0;

  constructor(data?: PartialMessage<ChunkStatistics>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.ChunkStatistics";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "total_chunks", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "avg_chunk_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "min_chunk_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "max_chunk_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "total_content_length", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChunkStatistics {
    return new ChunkStatistics().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChunkStatistics {
    return new ChunkStatistics().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChunkStatistics {
    return new ChunkStatistics().fromJsonString(jsonString, options);
  }

  static equals(a: ChunkStatistics | PlainMessage<ChunkStatistics> | undefined, b: ChunkStatistics | PlainMessage<ChunkStatistics> | undefined): boolean {
    return proto3.util.equals(ChunkStatistics, a, b);
  }
}

/**
 * ProposeChunksRequest - Generate chunk boundary proposals for a document
 *
 * @generated from message bibliophage.v1alpha3.ProposeChunksRequest
 */
export class ProposeChunksRequest extends Message<ProposeChunksRequest> {
  /**
   * Document ID to chunk
   *
   * @generated from field: string document_id = 1;
   */
  documentId = "";

  /**
   * Chunking configuration
   *
   * @generated from field: bibliophage.v1alpha3.ChunkingConfig config = 2;
   */
  config?: ChunkingConfig;

  constructor(data?: PartialMessage<ProposeChunksRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.ProposeChunksRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "config", kind: "message", T: ChunkingConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProposeChunksRequest {
    return new ProposeChunksRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProposeChunksRequest {
    return new ProposeChunksRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProposeChunksRequest {
    return new ProposeChunksRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ProposeChunksRequest | PlainMessage<ProposeChunksRequest> | undefined, b: ProposeChunksRequest | PlainMessage<ProposeChunksRequest> | undefined): boolean {
    return proto3.util.equals(ProposeChunksRequest, a, b);
  }
}

/**
 * ProposeChunksResponse - Result of chunk proposal generation
 *
 * @generated from message bibliophage.v1alpha3.ProposeChunksResponse
 */
export class ProposeChunksResponse extends Message<ProposeChunksResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * Proposed chunks (null if operation failed)
   *
   * @generated from field: optional bibliophage.v1alpha3.ChunkProposal proposal = 3;
   */
  proposal?: ChunkProposal;

  constructor(data?: PartialMessage<ProposeChunksResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.ProposeChunksResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "proposal", kind: "message", T: ChunkProposal, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProposeChunksResponse {
    return new ProposeChunksResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProposeChunksResponse {
    return new ProposeChunksResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProposeChunksResponse {
    return new ProposeChunksResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ProposeChunksResponse | PlainMessage<ProposeChunksResponse> | undefined, b: ProposeChunksResponse | PlainMessage<ProposeChunksResponse> | undefined): boolean {
    return proto3.util.equals(ProposeChunksResponse, a, b);
  }
}

/**
 * EmbedDocumentRequest - Embed a document with specified or generated boundaries
 *
 * @generated from message bibliophage.v1alpha3.EmbedDocumentRequest
 */
export class EmbedDocumentRequest extends Message<EmbedDocumentRequest> {
  /**
   * Document ID to embed
   *
   * @generated from field: string document_id = 1;
   */
  documentId = "";

  /**
   * Chunking configuration (used to generate boundaries if not provided)
   *
   * @generated from field: bibliophage.v1alpha3.ChunkingConfig config = 2;
   */
  config?: ChunkingConfig;

  /**
   * Optional: Pre-defined chunk boundaries (if not provided, will be generated from config)
   *
   * @generated from field: repeated bibliophage.v1alpha3.ChunkBoundary boundaries = 3;
   */
  boundaries: ChunkBoundary[] = [];

  constructor(data?: PartialMessage<EmbedDocumentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.EmbedDocumentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "config", kind: "message", T: ChunkingConfig },
    { no: 3, name: "boundaries", kind: "message", T: ChunkBoundary, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EmbedDocumentRequest {
    return new EmbedDocumentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EmbedDocumentRequest {
    return new EmbedDocumentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EmbedDocumentRequest {
    return new EmbedDocumentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: EmbedDocumentRequest | PlainMessage<EmbedDocumentRequest> | undefined, b: EmbedDocumentRequest | PlainMessage<EmbedDocumentRequest> | undefined): boolean {
    return proto3.util.equals(EmbedDocumentRequest, a, b);
  }
}

/**
 * EmbedDocumentResponse - Result of document embedding
 *
 * @generated from message bibliophage.v1alpha3.EmbedDocumentResponse
 */
export class EmbedDocumentResponse extends Message<EmbedDocumentResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * Embedding status after operation
   *
   * @generated from field: optional bibliophage.v1alpha3.EmbeddingStatus embedding_status = 3;
   */
  embeddingStatus?: EmbeddingStatus;

  constructor(data?: PartialMessage<EmbedDocumentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.EmbedDocumentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "embedding_status", kind: "message", T: EmbeddingStatus, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EmbedDocumentResponse {
    return new EmbedDocumentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EmbedDocumentResponse {
    return new EmbedDocumentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EmbedDocumentResponse {
    return new EmbedDocumentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: EmbedDocumentResponse | PlainMessage<EmbedDocumentResponse> | undefined, b: EmbedDocumentResponse | PlainMessage<EmbedDocumentResponse> | undefined): boolean {
    return proto3.util.equals(EmbedDocumentResponse, a, b);
  }
}

/**
 * GetChunkBoundariesRequest - Retrieve existing chunk boundaries for a document
 *
 * @generated from message bibliophage.v1alpha3.GetChunkBoundariesRequest
 */
export class GetChunkBoundariesRequest extends Message<GetChunkBoundariesRequest> {
  /**
   * Document ID to retrieve boundaries for
   *
   * @generated from field: string document_id = 1;
   */
  documentId = "";

  constructor(data?: PartialMessage<GetChunkBoundariesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.GetChunkBoundariesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChunkBoundariesRequest {
    return new GetChunkBoundariesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChunkBoundariesRequest {
    return new GetChunkBoundariesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChunkBoundariesRequest {
    return new GetChunkBoundariesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetChunkBoundariesRequest | PlainMessage<GetChunkBoundariesRequest> | undefined, b: GetChunkBoundariesRequest | PlainMessage<GetChunkBoundariesRequest> | undefined): boolean {
    return proto3.util.equals(GetChunkBoundariesRequest, a, b);
  }
}

/**
 * GetChunkBoundariesResponse - Result of retrieving chunk boundaries
 *
 * @generated from message bibliophage.v1alpha3.GetChunkBoundariesResponse
 */
export class GetChunkBoundariesResponse extends Message<GetChunkBoundariesResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * Array of chunk boundaries (null if document has no boundaries)
   *
   * @generated from field: repeated bibliophage.v1alpha3.ChunkBoundary boundaries = 3;
   */
  boundaries: ChunkBoundary[] = [];

  /**
   * Configuration used to generate these boundaries
   *
   * @generated from field: optional bibliophage.v1alpha3.ChunkingConfig config = 4;
   */
  config?: ChunkingConfig;

  /**
   * Current embedding status
   *
   * @generated from field: optional bibliophage.v1alpha3.EmbeddingStatus embedding_status = 5;
   */
  embeddingStatus?: EmbeddingStatus;

  constructor(data?: PartialMessage<GetChunkBoundariesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.GetChunkBoundariesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "boundaries", kind: "message", T: ChunkBoundary, repeated: true },
    { no: 4, name: "config", kind: "message", T: ChunkingConfig, opt: true },
    { no: 5, name: "embedding_status", kind: "message", T: EmbeddingStatus, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChunkBoundariesResponse {
    return new GetChunkBoundariesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChunkBoundariesResponse {
    return new GetChunkBoundariesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChunkBoundariesResponse {
    return new GetChunkBoundariesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetChunkBoundariesResponse | PlainMessage<GetChunkBoundariesResponse> | undefined, b: GetChunkBoundariesResponse | PlainMessage<GetChunkBoundariesResponse> | undefined): boolean {
    return proto3.util.equals(GetChunkBoundariesResponse, a, b);
  }
}

/**
 * UpdateChunkBoundariesRequest - Modify chunk boundaries (marks embeddings stale)
 *
 * @generated from message bibliophage.v1alpha3.UpdateChunkBoundariesRequest
 */
export class UpdateChunkBoundariesRequest extends Message<UpdateChunkBoundariesRequest> {
  /**
   * Document ID to update boundaries for
   *
   * @generated from field: string document_id = 1;
   */
  documentId = "";

  /**
   * Updated chunk boundaries
   *
   * @generated from field: repeated bibliophage.v1alpha3.ChunkBoundary boundaries = 2;
   */
  boundaries: ChunkBoundary[] = [];

  /**
   * Configuration used for these boundaries
   *
   * @generated from field: bibliophage.v1alpha3.ChunkingConfig config = 3;
   */
  config?: ChunkingConfig;

  constructor(data?: PartialMessage<UpdateChunkBoundariesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.UpdateChunkBoundariesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "boundaries", kind: "message", T: ChunkBoundary, repeated: true },
    { no: 3, name: "config", kind: "message", T: ChunkingConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateChunkBoundariesRequest {
    return new UpdateChunkBoundariesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateChunkBoundariesRequest {
    return new UpdateChunkBoundariesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateChunkBoundariesRequest {
    return new UpdateChunkBoundariesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateChunkBoundariesRequest | PlainMessage<UpdateChunkBoundariesRequest> | undefined, b: UpdateChunkBoundariesRequest | PlainMessage<UpdateChunkBoundariesRequest> | undefined): boolean {
    return proto3.util.equals(UpdateChunkBoundariesRequest, a, b);
  }
}

/**
 * UpdateChunkBoundariesResponse - Result of updating chunk boundaries
 *
 * @generated from message bibliophage.v1alpha3.UpdateChunkBoundariesResponse
 */
export class UpdateChunkBoundariesResponse extends Message<UpdateChunkBoundariesResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * Updated boundaries
   *
   * @generated from field: repeated bibliophage.v1alpha3.ChunkBoundary boundaries = 3;
   */
  boundaries: ChunkBoundary[] = [];

  /**
   * Embedding status (embeddings_current should be false)
   *
   * @generated from field: optional bibliophage.v1alpha3.EmbeddingStatus embedding_status = 4;
   */
  embeddingStatus?: EmbeddingStatus;

  constructor(data?: PartialMessage<UpdateChunkBoundariesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.UpdateChunkBoundariesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "boundaries", kind: "message", T: ChunkBoundary, repeated: true },
    { no: 4, name: "embedding_status", kind: "message", T: EmbeddingStatus, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateChunkBoundariesResponse {
    return new UpdateChunkBoundariesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateChunkBoundariesResponse {
    return new UpdateChunkBoundariesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateChunkBoundariesResponse {
    return new UpdateChunkBoundariesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateChunkBoundariesResponse | PlainMessage<UpdateChunkBoundariesResponse> | undefined, b: UpdateChunkBoundariesResponse | PlainMessage<UpdateChunkBoundariesResponse> | undefined): boolean {
    return proto3.util.equals(UpdateChunkBoundariesResponse, a, b);
  }
}

/**
 * DeleteEmbeddingsRequest - Remove all embeddings for a document
 *
 * @generated from message bibliophage.v1alpha3.DeleteEmbeddingsRequest
 */
export class DeleteEmbeddingsRequest extends Message<DeleteEmbeddingsRequest> {
  /**
   * Document ID to delete embeddings for
   *
   * @generated from field: string document_id = 1;
   */
  documentId = "";

  constructor(data?: PartialMessage<DeleteEmbeddingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteEmbeddingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteEmbeddingsRequest {
    return new DeleteEmbeddingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteEmbeddingsRequest {
    return new DeleteEmbeddingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteEmbeddingsRequest {
    return new DeleteEmbeddingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteEmbeddingsRequest | PlainMessage<DeleteEmbeddingsRequest> | undefined, b: DeleteEmbeddingsRequest | PlainMessage<DeleteEmbeddingsRequest> | undefined): boolean {
    return proto3.util.equals(DeleteEmbeddingsRequest, a, b);
  }
}

/**
 * DeleteEmbeddingsResponse - Result of deleting embeddings
 *
 * @generated from message bibliophage.v1alpha3.DeleteEmbeddingsResponse
 */
export class DeleteEmbeddingsResponse extends Message<DeleteEmbeddingsResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * Number of chunks deleted
   *
   * @generated from field: int32 chunks_deleted = 3;
   */
  chunksDeleted = 0;

  constructor(data?: PartialMessage<DeleteEmbeddingsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteEmbeddingsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "chunks_deleted", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteEmbeddingsResponse {
    return new DeleteEmbeddingsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteEmbeddingsResponse {
    return new DeleteEmbeddingsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteEmbeddingsResponse {
    return new DeleteEmbeddingsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteEmbeddingsResponse | PlainMessage<DeleteEmbeddingsResponse> | undefined, b: DeleteEmbeddingsResponse | PlainMessage<DeleteEmbeddingsResponse> | undefined): boolean {
    return proto3.util.equals(DeleteEmbeddingsResponse, a, b);
  }
}

