// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file bibliophage/v1alpha3/graph.proto (package bibliophage.v1alpha3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateEdgeRequest, CreateEdgeResponse, CreateNodeRequest, CreateNodeResponse, DeleteEdgeRequest, DeleteEdgeResponse, DeleteNodeRequest, DeleteNodeResponse } from "./graph_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bibliophage.v1alpha3.GraphService
 */
export const GraphService = {
  typeName: "bibliophage.v1alpha3.GraphService",
  methods: {
    /**
     * @generated from rpc bibliophage.v1alpha3.GraphService.CreateNode
     */
    createNode: {
      name: "CreateNode",
      I: CreateNodeRequest,
      O: CreateNodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.GraphService.CreateEdge
     */
    createEdge: {
      name: "CreateEdge",
      I: CreateEdgeRequest,
      O: CreateEdgeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.GraphService.DeleteNode
     */
    deleteNode: {
      name: "DeleteNode",
      I: DeleteNodeRequest,
      O: DeleteNodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.GraphService.DeleteEdge
     */
    deleteEdge: {
      name: "DeleteEdge",
      I: DeleteEdgeRequest,
      O: DeleteEdgeResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

