// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file bibliophage/v1alpha3/graph.proto (package bibliophage.v1alpha3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Struct } from "@bufbuild/protobuf";
import { DocumentListItem } from "./document_pb.js";

/**
 * Node represents a vertex in the knowledge graph
 *
 * @generated from message bibliophage.v1alpha3.Node
 */
export class Node extends Message<Node> {
  /**
   * Unique identifier (assigned by the system)
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Type identifier (e.g., "character", "location", "document")
   * References a TypeDefinition
   *
   * @generated from field: string type_id = 2;
   */
  typeId = "";

  /**
   * Dynamic properties validated against the type's schema
   * Struct works like JSON
   *
   * @generated from field: google.protobuf.Struct properties = 3;
   */
  properties?: Struct;

  constructor(data?: PartialMessage<Node>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.Node";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "properties", kind: "message", T: Struct },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Node {
    return new Node().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Node {
    return new Node().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Node {
    return new Node().fromJsonString(jsonString, options);
  }

  static equals(a: Node | PlainMessage<Node> | undefined, b: Node | PlainMessage<Node> | undefined): boolean {
    return proto3.util.equals(Node, a, b);
  }
}

/**
 * Edge represents a relationship between two nodes
 *
 * @generated from message bibliophage.v1alpha3.Edge
 */
export class Edge extends Message<Edge> {
  /**
   * Unique identifier (assigned by the system)
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Relationship type (e.g., "located_in", "knows", "owns")
   *
   * @generated from field: string relationship = 2;
   */
  relationship = "";

  /**
   * Whether this edge has a direction (A → B vs A — B)
   *
   * @generated from field: bool directed = 3;
   */
  directed = false;

  /**
   * Source node ID (or "node A" for undirected edges)
   *
   * @generated from field: string node_a = 4;
   */
  nodeA = "";

  /**
   * Target node ID (or "node B" for undirected edges)
   *
   * @generated from field: string node_b = 5;
   */
  nodeB = "";

  constructor(data?: PartialMessage<Edge>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.Edge";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "relationship", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "directed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "node_a", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "node_b", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Edge {
    return new Edge().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Edge {
    return new Edge().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Edge {
    return new Edge().fromJsonString(jsonString, options);
  }

  static equals(a: Edge | PlainMessage<Edge> | undefined, b: Edge | PlainMessage<Edge> | undefined): boolean {
    return proto3.util.equals(Edge, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.CreateNodeRequest
 */
export class CreateNodeRequest extends Message<CreateNodeRequest> {
  /**
   * Type identifier for this node
   *
   * @generated from field: string type_id = 1;
   */
  typeId = "";

  /**
   * Properties for this node (validated against type schema)
   *
   * @generated from field: google.protobuf.Struct properties = 2;
   */
  properties?: Struct;

  constructor(data?: PartialMessage<CreateNodeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.CreateNodeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "properties", kind: "message", T: Struct },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateNodeRequest {
    return new CreateNodeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateNodeRequest {
    return new CreateNodeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateNodeRequest {
    return new CreateNodeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateNodeRequest | PlainMessage<CreateNodeRequest> | undefined, b: CreateNodeRequest | PlainMessage<CreateNodeRequest> | undefined): boolean {
    return proto3.util.equals(CreateNodeRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.CreateNodeResponse
 */
export class CreateNodeResponse extends Message<CreateNodeResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The created node with assigned ID
   *
   * @generated from field: bibliophage.v1alpha3.Node node = 3;
   */
  node?: Node;

  constructor(data?: PartialMessage<CreateNodeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.CreateNodeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "node", kind: "message", T: Node },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateNodeResponse {
    return new CreateNodeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateNodeResponse {
    return new CreateNodeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateNodeResponse {
    return new CreateNodeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateNodeResponse | PlainMessage<CreateNodeResponse> | undefined, b: CreateNodeResponse | PlainMessage<CreateNodeResponse> | undefined): boolean {
    return proto3.util.equals(CreateNodeResponse, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.CreateEdgeRequest
 */
export class CreateEdgeRequest extends Message<CreateEdgeRequest> {
  /**
   * Relationship type (e.g., "located_in", "member_of")
   *
   * @generated from field: string relationship = 1;
   */
  relationship = "";

  /**
   * Whether this edge is directed
   *
   * @generated from field: bool directed = 2;
   */
  directed = false;

  /**
   * Source node ID
   *
   * @generated from field: string source_node_id = 3;
   */
  sourceNodeId = "";

  /**
   * Target node ID
   *
   * @generated from field: string target_node_id = 4;
   */
  targetNodeId = "";

  constructor(data?: PartialMessage<CreateEdgeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.CreateEdgeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "relationship", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "directed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "source_node_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "target_node_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateEdgeRequest {
    return new CreateEdgeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateEdgeRequest {
    return new CreateEdgeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateEdgeRequest {
    return new CreateEdgeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateEdgeRequest | PlainMessage<CreateEdgeRequest> | undefined, b: CreateEdgeRequest | PlainMessage<CreateEdgeRequest> | undefined): boolean {
    return proto3.util.equals(CreateEdgeRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.CreateEdgeResponse
 */
export class CreateEdgeResponse extends Message<CreateEdgeResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The created edge with assigned ID
   *
   * @generated from field: bibliophage.v1alpha3.Edge edge = 3;
   */
  edge?: Edge;

  constructor(data?: PartialMessage<CreateEdgeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.CreateEdgeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "edge", kind: "message", T: Edge },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateEdgeResponse {
    return new CreateEdgeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateEdgeResponse {
    return new CreateEdgeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateEdgeResponse {
    return new CreateEdgeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateEdgeResponse | PlainMessage<CreateEdgeResponse> | undefined, b: CreateEdgeResponse | PlainMessage<CreateEdgeResponse> | undefined): boolean {
    return proto3.util.equals(CreateEdgeResponse, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.DeleteNodeRequest
 */
export class DeleteNodeRequest extends Message<DeleteNodeRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DeleteNodeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteNodeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteNodeRequest {
    return new DeleteNodeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteNodeRequest {
    return new DeleteNodeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteNodeRequest {
    return new DeleteNodeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteNodeRequest | PlainMessage<DeleteNodeRequest> | undefined, b: DeleteNodeRequest | PlainMessage<DeleteNodeRequest> | undefined): boolean {
    return proto3.util.equals(DeleteNodeRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.DeleteNodeResponse
 */
export class DeleteNodeResponse extends Message<DeleteNodeResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<DeleteNodeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteNodeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteNodeResponse {
    return new DeleteNodeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteNodeResponse {
    return new DeleteNodeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteNodeResponse {
    return new DeleteNodeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteNodeResponse | PlainMessage<DeleteNodeResponse> | undefined, b: DeleteNodeResponse | PlainMessage<DeleteNodeResponse> | undefined): boolean {
    return proto3.util.equals(DeleteNodeResponse, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.DeleteEdgeRequest
 */
export class DeleteEdgeRequest extends Message<DeleteEdgeRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DeleteEdgeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteEdgeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteEdgeRequest {
    return new DeleteEdgeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteEdgeRequest {
    return new DeleteEdgeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteEdgeRequest {
    return new DeleteEdgeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteEdgeRequest | PlainMessage<DeleteEdgeRequest> | undefined, b: DeleteEdgeRequest | PlainMessage<DeleteEdgeRequest> | undefined): boolean {
    return proto3.util.equals(DeleteEdgeRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.DeleteEdgeResponse
 */
export class DeleteEdgeResponse extends Message<DeleteEdgeResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<DeleteEdgeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteEdgeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteEdgeResponse {
    return new DeleteEdgeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteEdgeResponse {
    return new DeleteEdgeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteEdgeResponse {
    return new DeleteEdgeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteEdgeResponse | PlainMessage<DeleteEdgeResponse> | undefined, b: DeleteEdgeResponse | PlainMessage<DeleteEdgeResponse> | undefined): boolean {
    return proto3.util.equals(DeleteEdgeResponse, a, b);
  }
}

/**
 * Fetch all neighbours of a single node in one round-trip.
 *
 * @generated from message bibliophage.v1alpha3.GetNeighboursRequest
 */
export class GetNeighboursRequest extends Message<GetNeighboursRequest> {
  /**
   * ID of the node whose neighbourhood should be returned
   *
   * @generated from field: string document_id = 1;
   */
  documentId = "";

  constructor(data?: PartialMessage<GetNeighboursRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.GetNeighboursRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetNeighboursRequest {
    return new GetNeighboursRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetNeighboursRequest {
    return new GetNeighboursRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetNeighboursRequest {
    return new GetNeighboursRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetNeighboursRequest | PlainMessage<GetNeighboursRequest> | undefined, b: GetNeighboursRequest | PlainMessage<GetNeighboursRequest> | undefined): boolean {
    return proto3.util.equals(GetNeighboursRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.GetNeighboursResponse
 */
export class GetNeighboursResponse extends Message<GetNeighboursResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * Lightweight summaries of every adjacent document.
   * Use DocumentService.GetDocument to retrieve full content.
   *
   * @generated from field: repeated bibliophage.v1alpha3.DocumentListItem neighbours = 3;
   */
  neighbours: DocumentListItem[] = [];

  /**
   * Every edge incident to the requested node
   *
   * @generated from field: repeated bibliophage.v1alpha3.Edge edges = 4;
   */
  edges: Edge[] = [];

  constructor(data?: PartialMessage<GetNeighboursResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.GetNeighboursResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "neighbours", kind: "message", T: DocumentListItem, repeated: true },
    { no: 4, name: "edges", kind: "message", T: Edge, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetNeighboursResponse {
    return new GetNeighboursResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetNeighboursResponse {
    return new GetNeighboursResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetNeighboursResponse {
    return new GetNeighboursResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetNeighboursResponse | PlainMessage<GetNeighboursResponse> | undefined, b: GetNeighboursResponse | PlainMessage<GetNeighboursResponse> | undefined): boolean {
    return proto3.util.equals(GetNeighboursResponse, a, b);
  }
}

/**
 * Fetch every edge whose endpoints both lie in the provided node set.
 *
 * @generated from message bibliophage.v1alpha3.ListEdgesRequest
 */
export class ListEdgesRequest extends Message<ListEdgesRequest> {
  /**
   * IDs of nodes to consider. Only edges with both endpoints in this
   * set are returned.
   *
   * @generated from field: repeated string document_ids = 1;
   */
  documentIds: string[] = [];

  constructor(data?: PartialMessage<ListEdgesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.ListEdgesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "document_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEdgesRequest {
    return new ListEdgesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEdgesRequest {
    return new ListEdgesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEdgesRequest {
    return new ListEdgesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListEdgesRequest | PlainMessage<ListEdgesRequest> | undefined, b: ListEdgesRequest | PlainMessage<ListEdgesRequest> | undefined): boolean {
    return proto3.util.equals(ListEdgesRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.ListEdgesResponse
 */
export class ListEdgesResponse extends Message<ListEdgesResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * @generated from field: repeated bibliophage.v1alpha3.Edge edges = 3;
   */
  edges: Edge[] = [];

  constructor(data?: PartialMessage<ListEdgesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.ListEdgesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "edges", kind: "message", T: Edge, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEdgesResponse {
    return new ListEdgesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEdgesResponse {
    return new ListEdgesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEdgesResponse {
    return new ListEdgesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListEdgesResponse | PlainMessage<ListEdgesResponse> | undefined, b: ListEdgesResponse | PlainMessage<ListEdgesResponse> | undefined): boolean {
    return proto3.util.equals(ListEdgesResponse, a, b);
  }
}

