// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file bibliophage/v1alpha3/pdf.proto (package bibliophage.v1alpha3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { Tag } from "./common_pb.js";

/**
 * Pdf represents a PDF document in the system
 * Does not actually contain the raw data, only metadata
 *
 * @generated from message bibliophage.v1alpha3.Pdf
 */
export class Pdf extends Message<Pdf> {
  /**
   * Unique identifier for this PDF (assigned by the backend)
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Human-readable name (e.g., "Monster Manual", "Player's Handbook")
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * Which RPG system(s) this belongs to
   * Examples:
   *   Single system: ["Call of Cthulhu"]
   *   Multi-system: ["D&D 3.5e", "Pathfinder 1e"]
   *   System-agnostic: ["Generic"]
   * Must contain at least one value
   *
   * @generated from field: repeated string systems = 3;
   */
  systems: string[] = [];

  /**
   * Type of publication (e.g., "Core Rulebook", "Adventure", "Supplement")
   *
   * @generated from field: string type = 4;
   */
  type = "";

  /**
   * Number of pages in the PDF
   *
   * @generated from field: int32 page_count = 5;
   */
  pageCount = 0;

  /**
   * When this PDF was first loaded into the system
   *
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * When this PDF was last updated
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp;

  /**
   * File size in bytes
   *
   * @generated from field: int64 file_size = 8;
   */
  fileSize = protoInt64.zero;

  /**
   * Number of batches processed by Docling (usually corresponds to chapters/sections)
   *
   * @generated from field: int32 batch_count = 9;
   */
  batchCount = 0;

  /**
   * Number of text chunks created for vector embeddings
   *
   * @generated from field: int32 vector_chunk_count = 10;
   */
  vectorChunkCount = 0;

  /**
   * Structured tags for organization (name + multiple values)
   *
   * @generated from field: repeated bibliophage.v1alpha3.Tag tags = 11;
   */
  tags: Tag[] = [];

  /**
   * Markdown content extracted from the PDF (optional, only populated for GetPdf)
   * Contains concatenated markdown from all processed batches
   * Not included in search results to keep responses lightweight
   *
   * @generated from field: optional string content = 12;
   */
  content?: string;

  constructor(data?: PartialMessage<Pdf>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.Pdf";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "systems", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "page_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
    { no: 7, name: "updated_at", kind: "message", T: Timestamp },
    { no: 8, name: "file_size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "batch_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "vector_chunk_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "tags", kind: "message", T: Tag, repeated: true },
    { no: 12, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Pdf {
    return new Pdf().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Pdf {
    return new Pdf().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Pdf {
    return new Pdf().fromJsonString(jsonString, options);
  }

  static equals(a: Pdf | PlainMessage<Pdf> | undefined, b: Pdf | PlainMessage<Pdf> | undefined): boolean {
    return proto3.util.equals(Pdf, a, b);
  }
}

/**
 * PdfListItem represents a PDF in list/search results
 * Contains metadata only - never includes the actual PDF file data
 * Structurally identical to Pdf, but semantically distinct for search responses
 * This separation ensures future changes to search results don't affect other operations
 *
 * @generated from message bibliophage.v1alpha3.PdfListItem
 */
export class PdfListItem extends Message<PdfListItem> {
  /**
   * Unique identifier for this PDF
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Human-readable name
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * Which RPG system(s) this belongs to (see Pdf message for examples)
   *
   * @generated from field: repeated string systems = 3;
   */
  systems: string[] = [];

  /**
   * Type of publication
   *
   * @generated from field: string type = 4;
   */
  type = "";

  /**
   * Number of pages in the PDF
   *
   * @generated from field: int32 page_count = 5;
   */
  pageCount = 0;

  /**
   * When this PDF was first loaded into the system
   *
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * When this PDF was last updated
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp;

  /**
   * File size in bytes
   *
   * @generated from field: int64 file_size = 8;
   */
  fileSize = protoInt64.zero;

  /**
   * Number of batches processed by Docling
   *
   * @generated from field: int32 batch_count = 9;
   */
  batchCount = 0;

  /**
   * Number of text chunks created for vector embeddings
   *
   * @generated from field: int32 vector_chunk_count = 10;
   */
  vectorChunkCount = 0;

  /**
   * Structured tags for organization
   *
   * @generated from field: repeated bibliophage.v1alpha3.Tag tags = 11;
   */
  tags: Tag[] = [];

  constructor(data?: PartialMessage<PdfListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.PdfListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "systems", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "page_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
    { no: 7, name: "updated_at", kind: "message", T: Timestamp },
    { no: 8, name: "file_size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "batch_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "vector_chunk_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "tags", kind: "message", T: Tag, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PdfListItem {
    return new PdfListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PdfListItem {
    return new PdfListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PdfListItem {
    return new PdfListItem().fromJsonString(jsonString, options);
  }

  static equals(a: PdfListItem | PlainMessage<PdfListItem> | undefined, b: PdfListItem | PlainMessage<PdfListItem> | undefined): boolean {
    return proto3.util.equals(PdfListItem, a, b);
  }
}

/**
 * LoadPdfRequest - Load a PDF into the system
 *
 * @generated from message bibliophage.v1alpha3.LoadPdfRequest
 */
export class LoadPdfRequest extends Message<LoadPdfRequest> {
  /**
   * The PDF document metadata to load
   *
   * @generated from field: bibliophage.v1alpha3.Pdf pdf = 1;
   */
  pdf?: Pdf;

  /**
   * The actual PDF file data (bytes)
   *
   * @generated from field: bytes file_data = 2;
   */
  fileData = new Uint8Array(0);

  constructor(data?: PartialMessage<LoadPdfRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.LoadPdfRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pdf", kind: "message", T: Pdf },
    { no: 2, name: "file_data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LoadPdfRequest {
    return new LoadPdfRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LoadPdfRequest {
    return new LoadPdfRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LoadPdfRequest {
    return new LoadPdfRequest().fromJsonString(jsonString, options);
  }

  static equals(a: LoadPdfRequest | PlainMessage<LoadPdfRequest> | undefined, b: LoadPdfRequest | PlainMessage<LoadPdfRequest> | undefined): boolean {
    return proto3.util.equals(LoadPdfRequest, a, b);
  }
}

/**
 * LoadPdfResponse - Result of loading a PDF
 *
 * @generated from message bibliophage.v1alpha3.LoadPdfResponse
 */
export class LoadPdfResponse extends Message<LoadPdfResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The loaded PDF with assigned ID and metadata
   *
   * @generated from field: bibliophage.v1alpha3.Pdf pdf = 3;
   */
  pdf?: Pdf;

  constructor(data?: PartialMessage<LoadPdfResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.LoadPdfResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "pdf", kind: "message", T: Pdf },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LoadPdfResponse {
    return new LoadPdfResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LoadPdfResponse {
    return new LoadPdfResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LoadPdfResponse {
    return new LoadPdfResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LoadPdfResponse | PlainMessage<LoadPdfResponse> | undefined, b: LoadPdfResponse | PlainMessage<LoadPdfResponse> | undefined): boolean {
    return proto3.util.equals(LoadPdfResponse, a, b);
  }
}

