// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file bibliophage/v1alpha3/tag.proto (package bibliophage.v1alpha3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Tag represents a named category with multiple values
 * Example: {"name": "genre", "values": ["adventure", "fantasy", "noire"]}
 *
 * @generated from message bibliophage.v1alpha3.Tag
 */
export class Tag extends Message<Tag> {
  /**
   * Name of the tag (e.g., "genre", "world", "category", "tone")
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * UUID for this specific tag
   *
   * @generated from field: string id = 2;
   */
  id = "";

  /**
   * hex coded colour
   * TODO: should and can we validate this in the fronted / API too?
   *
   * @generated from field: optional string colour = 3;
   */
  colour?: string;

  /**
   * Values associated with this tag
   *
   * @generated from field: repeated bibliophage.v1alpha3.TagValue values = 4;
   */
  values: TagValue[] = [];

  /**
   * number of documents this tag applies to
   *
   * @generated from field: optional int32 document_count = 5;
   */
  documentCount?: number;

  /**
   * number of distinct values this tag has
   *
   * @generated from field: optional int32 value_count = 6;
   */
  valueCount?: number;

  constructor(data?: PartialMessage<Tag>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.Tag";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "colour", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "values", kind: "message", T: TagValue, repeated: true },
    { no: 5, name: "document_count", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "value_count", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Tag {
    return new Tag().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Tag {
    return new Tag().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Tag {
    return new Tag().fromJsonString(jsonString, options);
  }

  static equals(a: Tag | PlainMessage<Tag> | undefined, b: Tag | PlainMessage<Tag> | undefined): boolean {
    return proto3.util.equals(Tag, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.TagValue
 */
export class TagValue extends Message<TagValue> {
  /**
   * Value for a given tag (e.g., "fantasy", "arrakis", "rulebook", "mysterious")
   *
   * @generated from field: string value = 1;
   */
  value = "";

  /**
   * number of documents this tag value applies to
   *
   * @generated from field: optional int32 document_count = 2;
   */
  documentCount?: number;

  constructor(data?: PartialMessage<TagValue>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.TagValue";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_count", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TagValue {
    return new TagValue().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TagValue {
    return new TagValue().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TagValue {
    return new TagValue().fromJsonString(jsonString, options);
  }

  static equals(a: TagValue | PlainMessage<TagValue> | undefined, b: TagValue | PlainMessage<TagValue> | undefined): boolean {
    return proto3.util.equals(TagValue, a, b);
  }
}

/**
 * TagFilter represents a filter for tag-based searches
 * Matches items where tag.name == name AND any value in tag.values matches value
 *
 * @generated from message bibliophage.v1alpha3.TagFilter
 */
export class TagFilter extends Message<TagFilter> {
  /**
   * Name of the tag to filter on (e.g., "genre", "campaign")
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Value to match against (e.g., "fantasy", "core-rules")
   *
   * @generated from field: string value = 2;
   */
  value = "";

  constructor(data?: PartialMessage<TagFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.TagFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TagFilter {
    return new TagFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TagFilter {
    return new TagFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TagFilter {
    return new TagFilter().fromJsonString(jsonString, options);
  }

  static equals(a: TagFilter | PlainMessage<TagFilter> | undefined, b: TagFilter | PlainMessage<TagFilter> | undefined): boolean {
    return proto3.util.equals(TagFilter, a, b);
  }
}

/**
 * Create a new tag
 *
 * @generated from message bibliophage.v1alpha3.StoreTagRequest
 */
export class StoreTagRequest extends Message<StoreTagRequest> {
  /**
   * The tag to store (ID will be assigned by server)
   *
   * @generated from field: bibliophage.v1alpha3.Tag tag = 1;
   */
  tag?: Tag;

  constructor(data?: PartialMessage<StoreTagRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.StoreTagRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tag", kind: "message", T: Tag },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StoreTagRequest {
    return new StoreTagRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StoreTagRequest {
    return new StoreTagRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StoreTagRequest {
    return new StoreTagRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StoreTagRequest | PlainMessage<StoreTagRequest> | undefined, b: StoreTagRequest | PlainMessage<StoreTagRequest> | undefined): boolean {
    return proto3.util.equals(StoreTagRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.StoreTagResponse
 */
export class StoreTagResponse extends Message<StoreTagResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The stored tag with assigned ID
   *
   * @generated from field: bibliophage.v1alpha3.Tag tag = 3;
   */
  tag?: Tag;

  constructor(data?: PartialMessage<StoreTagResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.StoreTagResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tag", kind: "message", T: Tag },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StoreTagResponse {
    return new StoreTagResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StoreTagResponse {
    return new StoreTagResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StoreTagResponse {
    return new StoreTagResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StoreTagResponse | PlainMessage<StoreTagResponse> | undefined, b: StoreTagResponse | PlainMessage<StoreTagResponse> | undefined): boolean {
    return proto3.util.equals(StoreTagResponse, a, b);
  }
}

/**
 * retrieve a tag by id
 *
 * @generated from message bibliophage.v1alpha3.GetTagRequest
 */
export class GetTagRequest extends Message<GetTagRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * whether or not to return the tag with the document_count attribute
   * defaults to false
   *
   * @generated from field: optional bool count_docs = 2;
   */
  countDocs?: boolean;

  /**
   * whether or not to return the tag with the value_count attribute
   * defaults to false
   *
   * @generated from field: optional bool count_values = 3;
   */
  countValues?: boolean;

  constructor(data?: PartialMessage<GetTagRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.GetTagRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "count_docs", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 3, name: "count_values", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTagRequest {
    return new GetTagRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTagRequest {
    return new GetTagRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTagRequest {
    return new GetTagRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetTagRequest | PlainMessage<GetTagRequest> | undefined, b: GetTagRequest | PlainMessage<GetTagRequest> | undefined): boolean {
    return proto3.util.equals(GetTagRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.GetTagResponse
 */
export class GetTagResponse extends Message<GetTagResponse> {
  /**
   * Whether the operation succeeded
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The requested tag (null if not found)
   *
   * @generated from field: optional bibliophage.v1alpha3.Tag tag = 3;
   */
  tag?: Tag;

  constructor(data?: PartialMessage<GetTagResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.GetTagResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tag", kind: "message", T: Tag, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTagResponse {
    return new GetTagResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTagResponse {
    return new GetTagResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTagResponse {
    return new GetTagResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetTagResponse | PlainMessage<GetTagResponse> | undefined, b: GetTagResponse | PlainMessage<GetTagResponse> | undefined): boolean {
    return proto3.util.equals(GetTagResponse, a, b);
  }
}

/**
 * retrieve all tags matching a filter
 * if no filter, return all tags
 *
 * @generated from message bibliophage.v1alpha3.GetTagsRequest
 */
export class GetTagsRequest extends Message<GetTagsRequest> {
  /**
   * simple lowercase string match for now
   *
   * @generated from field: optional string name_filter = 1;
   */
  nameFilter?: string;

  /**
   * whether or not to return the tags with their document_count attribute
   * defaults to false
   *
   * @generated from field: optional bool count_docs = 2;
   */
  countDocs?: boolean;

  /**
   * whether or not to return the tags with their value_count attribute
   * defaults to false
   *
   * @generated from field: optional bool count_values = 3;
   */
  countValues?: boolean;

  constructor(data?: PartialMessage<GetTagsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.GetTagsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name_filter", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "count_docs", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 3, name: "count_values", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTagsRequest {
    return new GetTagsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTagsRequest {
    return new GetTagsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTagsRequest {
    return new GetTagsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetTagsRequest | PlainMessage<GetTagsRequest> | undefined, b: GetTagsRequest | PlainMessage<GetTagsRequest> | undefined): boolean {
    return proto3.util.equals(GetTagsRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.GetTagsResponse
 */
export class GetTagsResponse extends Message<GetTagsResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * the tags matching the filter 
   *
   * @generated from field: repeated bibliophage.v1alpha3.Tag tags = 3;
   */
  tags: Tag[] = [];

  constructor(data?: PartialMessage<GetTagsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.GetTagsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tags", kind: "message", T: Tag, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTagsResponse {
    return new GetTagsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTagsResponse {
    return new GetTagsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTagsResponse {
    return new GetTagsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetTagsResponse | PlainMessage<GetTagsResponse> | undefined, b: GetTagsResponse | PlainMessage<GetTagsResponse> | undefined): boolean {
    return proto3.util.equals(GetTagsResponse, a, b);
  }
}

/**
 * Delete a tag by ID
 *
 * @generated from message bibliophage.v1alpha3.DeleteTagRequest
 */
export class DeleteTagRequest extends Message<DeleteTagRequest> {
  /**
   * The unique ID of the tag to delete
   *
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DeleteTagRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteTagRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteTagRequest {
    return new DeleteTagRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteTagRequest {
    return new DeleteTagRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteTagRequest {
    return new DeleteTagRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteTagRequest | PlainMessage<DeleteTagRequest> | undefined, b: DeleteTagRequest | PlainMessage<DeleteTagRequest> | undefined): boolean {
    return proto3.util.equals(DeleteTagRequest, a, b);
  }
}

/**
 * DeleteTagResponse - Result of deleting a tag
 *
 * @generated from message bibliophage.v1alpha3.DeleteTagResponse
 */
export class DeleteTagResponse extends Message<DeleteTagResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<DeleteTagResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteTagResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteTagResponse {
    return new DeleteTagResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteTagResponse {
    return new DeleteTagResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteTagResponse {
    return new DeleteTagResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteTagResponse | PlainMessage<DeleteTagResponse> | undefined, b: DeleteTagResponse | PlainMessage<DeleteTagResponse> | undefined): boolean {
    return proto3.util.equals(DeleteTagResponse, a, b);
  }
}

/**
 * Rename an existing tag
 *
 * @generated from message bibliophage.v1alpha3.RenameTagRequest
 */
export class RenameTagRequest extends Message<RenameTagRequest> {
  /**
   * The tag id to update
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * new name
   *
   * @generated from field: string name = 2;
   */
  name = "";

  constructor(data?: PartialMessage<RenameTagRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.RenameTagRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RenameTagRequest {
    return new RenameTagRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RenameTagRequest {
    return new RenameTagRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RenameTagRequest {
    return new RenameTagRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RenameTagRequest | PlainMessage<RenameTagRequest> | undefined, b: RenameTagRequest | PlainMessage<RenameTagRequest> | undefined): boolean {
    return proto3.util.equals(RenameTagRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.RenameTagResponse
 */
export class RenameTagResponse extends Message<RenameTagResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The updated tag
   *
   * @generated from field: bibliophage.v1alpha3.Tag tag = 3;
   */
  tag?: Tag;

  constructor(data?: PartialMessage<RenameTagResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.RenameTagResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tag", kind: "message", T: Tag },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RenameTagResponse {
    return new RenameTagResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RenameTagResponse {
    return new RenameTagResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RenameTagResponse {
    return new RenameTagResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RenameTagResponse | PlainMessage<RenameTagResponse> | undefined, b: RenameTagResponse | PlainMessage<RenameTagResponse> | undefined): boolean {
    return proto3.util.equals(RenameTagResponse, a, b);
  }
}

/**
 * Change tag colour
 *
 * @generated from message bibliophage.v1alpha3.UpdateTagColourRequest
 */
export class UpdateTagColourRequest extends Message<UpdateTagColourRequest> {
  /**
   * The tag id to update
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * new colour
   *
   * @generated from field: string colour = 2;
   */
  colour = "";

  constructor(data?: PartialMessage<UpdateTagColourRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.UpdateTagColourRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "colour", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateTagColourRequest {
    return new UpdateTagColourRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateTagColourRequest {
    return new UpdateTagColourRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateTagColourRequest {
    return new UpdateTagColourRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateTagColourRequest | PlainMessage<UpdateTagColourRequest> | undefined, b: UpdateTagColourRequest | PlainMessage<UpdateTagColourRequest> | undefined): boolean {
    return proto3.util.equals(UpdateTagColourRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.UpdateTagColourResponse
 */
export class UpdateTagColourResponse extends Message<UpdateTagColourResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The updated tag
   *
   * @generated from field: bibliophage.v1alpha3.Tag tag = 3;
   */
  tag?: Tag;

  constructor(data?: PartialMessage<UpdateTagColourResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.UpdateTagColourResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tag", kind: "message", T: Tag },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateTagColourResponse {
    return new UpdateTagColourResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateTagColourResponse {
    return new UpdateTagColourResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateTagColourResponse {
    return new UpdateTagColourResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateTagColourResponse | PlainMessage<UpdateTagColourResponse> | undefined, b: UpdateTagColourResponse | PlainMessage<UpdateTagColourResponse> | undefined): boolean {
    return proto3.util.equals(UpdateTagColourResponse, a, b);
  }
}

/**
 * Store a new tag value
 *
 * @generated from message bibliophage.v1alpha3.StoreTagValueRequest
 */
export class StoreTagValueRequest extends Message<StoreTagValueRequest> {
  /**
   * ID of the tag this value is meant for
   *
   * @generated from field: string tag_id = 1;
   */
  tagId = "";

  /**
   * The tag value to store
   *
   * @generated from field: bibliophage.v1alpha3.TagValue tag_value = 2;
   */
  tagValue?: TagValue;

  constructor(data?: PartialMessage<StoreTagValueRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.StoreTagValueRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tag_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "tag_value", kind: "message", T: TagValue },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StoreTagValueRequest {
    return new StoreTagValueRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StoreTagValueRequest {
    return new StoreTagValueRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StoreTagValueRequest {
    return new StoreTagValueRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StoreTagValueRequest | PlainMessage<StoreTagValueRequest> | undefined, b: StoreTagValueRequest | PlainMessage<StoreTagValueRequest> | undefined): boolean {
    return proto3.util.equals(StoreTagValueRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.StoreTagValueResponse
 */
export class StoreTagValueResponse extends Message<StoreTagValueResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The stored tag value
   *
   * @generated from field: bibliophage.v1alpha3.TagValue tag_value = 3;
   */
  tagValue?: TagValue;

  constructor(data?: PartialMessage<StoreTagValueResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.StoreTagValueResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tag_value", kind: "message", T: TagValue },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StoreTagValueResponse {
    return new StoreTagValueResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StoreTagValueResponse {
    return new StoreTagValueResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StoreTagValueResponse {
    return new StoreTagValueResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StoreTagValueResponse | PlainMessage<StoreTagValueResponse> | undefined, b: StoreTagValueResponse | PlainMessage<StoreTagValueResponse> | undefined): boolean {
    return proto3.util.equals(StoreTagValueResponse, a, b);
  }
}

/**
 * Delete a tag value by ID
 *
 * @generated from message bibliophage.v1alpha3.DeleteTagValueRequest
 */
export class DeleteTagValueRequest extends Message<DeleteTagValueRequest> {
  /**
   * The unique ID of the tag value to delete
   *
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DeleteTagValueRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteTagValueRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteTagValueRequest {
    return new DeleteTagValueRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteTagValueRequest {
    return new DeleteTagValueRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteTagValueRequest {
    return new DeleteTagValueRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteTagValueRequest | PlainMessage<DeleteTagValueRequest> | undefined, b: DeleteTagValueRequest | PlainMessage<DeleteTagValueRequest> | undefined): boolean {
    return proto3.util.equals(DeleteTagValueRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.DeleteTagValueResponse
 */
export class DeleteTagValueResponse extends Message<DeleteTagValueResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<DeleteTagValueResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.DeleteTagValueResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteTagValueResponse {
    return new DeleteTagValueResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteTagValueResponse {
    return new DeleteTagValueResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteTagValueResponse {
    return new DeleteTagValueResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteTagValueResponse | PlainMessage<DeleteTagValueResponse> | undefined, b: DeleteTagValueResponse | PlainMessage<DeleteTagValueResponse> | undefined): boolean {
    return proto3.util.equals(DeleteTagValueResponse, a, b);
  }
}

/**
 * Rename an existing tag value
 *
 * @generated from message bibliophage.v1alpha3.RenameTagValueRequest
 */
export class RenameTagValueRequest extends Message<RenameTagValueRequest> {
  /**
   * The tag value id to update
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * new name
   *
   * @generated from field: string name = 2;
   */
  name = "";

  constructor(data?: PartialMessage<RenameTagValueRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.RenameTagValueRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RenameTagValueRequest {
    return new RenameTagValueRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RenameTagValueRequest {
    return new RenameTagValueRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RenameTagValueRequest {
    return new RenameTagValueRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RenameTagValueRequest | PlainMessage<RenameTagValueRequest> | undefined, b: RenameTagValueRequest | PlainMessage<RenameTagValueRequest> | undefined): boolean {
    return proto3.util.equals(RenameTagValueRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.v1alpha3.RenameTagValueResponse
 */
export class RenameTagValueResponse extends Message<RenameTagValueResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * The renamed tag value
   *
   * @generated from field: bibliophage.v1alpha3.TagValue tag_value = 3;
   */
  tagValue?: TagValue;

  constructor(data?: PartialMessage<RenameTagValueResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.v1alpha3.RenameTagValueResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tag_value", kind: "message", T: TagValue },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RenameTagValueResponse {
    return new RenameTagValueResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RenameTagValueResponse {
    return new RenameTagValueResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RenameTagValueResponse {
    return new RenameTagValueResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RenameTagValueResponse | PlainMessage<RenameTagValueResponse> | undefined, b: RenameTagValueResponse | PlainMessage<RenameTagValueResponse> | undefined): boolean {
    return proto3.util.equals(RenameTagValueResponse, a, b);
  }
}

