// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file bibliophage/v1alpha3/tag.proto (package bibliophage.v1alpha3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteTagRequest, DeleteTagResponse, DeleteTagValueRequest, DeleteTagValueResponse, GetTagRequest, GetTagResponse, GetTagsRequest, GetTagsResponse, RenameTagRequest, RenameTagResponse, RenameTagValueRequest, RenameTagValueResponse, StoreTagRequest, StoreTagResponse, StoreTagValueRequest, StoreTagValueResponse, UpdateTagColourRequest, UpdateTagColourResponse } from "./tag_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definitions - the API endpoints
 *
 * @generated from service bibliophage.v1alpha3.TagService
 */
export const TagService = {
  typeName: "bibliophage.v1alpha3.TagService",
  methods: {
    /**
     * @generated from rpc bibliophage.v1alpha3.TagService.StoreTag
     */
    storeTag: {
      name: "StoreTag",
      I: StoreTagRequest,
      O: StoreTagResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.TagService.DeleteTag
     */
    deleteTag: {
      name: "DeleteTag",
      I: DeleteTagRequest,
      O: DeleteTagResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.TagService.RenameTag
     */
    renameTag: {
      name: "RenameTag",
      I: RenameTagRequest,
      O: RenameTagResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.TagService.UpdateTagColour
     */
    updateTagColour: {
      name: "UpdateTagColour",
      I: UpdateTagColourRequest,
      O: UpdateTagColourResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.TagService.StoreTagValue
     */
    storeTagValue: {
      name: "StoreTagValue",
      I: StoreTagValueRequest,
      O: StoreTagValueResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.TagService.DeleteTagValue
     */
    deleteTagValue: {
      name: "DeleteTagValue",
      I: DeleteTagValueRequest,
      O: DeleteTagValueResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.TagService.RenameTagValue
     */
    renameTagValue: {
      name: "RenameTagValue",
      I: RenameTagValueRequest,
      O: RenameTagValueResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.TagService.GetTag
     */
    getTag: {
      name: "GetTag",
      I: GetTagRequest,
      O: GetTagResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha3.TagService.GetTags
     */
    getTags: {
      name: "GetTags",
      I: GetTagsRequest,
      O: GetTagsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

