# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: bibliophage/v1alpha2/document.proto

from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import bibliophage.v1alpha2.document_pb2 as bibliophage_dot_v1alpha2_dot_document__pb2


class DocumentService(Protocol):
    async def store_document(self, request: bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_document(self, request: bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_document(self, request: bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def search_documents(self, request: bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_document(self, request: bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DocumentServiceASGIApplication(ConnectASGIApplication):
    def __init__(self, service: DocumentService, *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/bibliophage.v1alpha2.DocumentService/StoreDocument": Endpoint.unary(
                    method=MethodInfo(
                        name="StoreDocument",
                        service_name="bibliophage.v1alpha2.DocumentService",
                        input=bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentRequest,
                        output=bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.store_document,
                ),
                "/bibliophage.v1alpha2.DocumentService/GetDocument": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDocument",
                        service_name="bibliophage.v1alpha2.DocumentService",
                        input=bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentRequest,
                        output=bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_document,
                ),
                "/bibliophage.v1alpha2.DocumentService/UpdateDocument": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateDocument",
                        service_name="bibliophage.v1alpha2.DocumentService",
                        input=bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentRequest,
                        output=bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_document,
                ),
                "/bibliophage.v1alpha2.DocumentService/SearchDocuments": Endpoint.unary(
                    method=MethodInfo(
                        name="SearchDocuments",
                        service_name="bibliophage.v1alpha2.DocumentService",
                        input=bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsRequest,
                        output=bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.search_documents,
                ),
                "/bibliophage.v1alpha2.DocumentService/DeleteDocument": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteDocument",
                        service_name="bibliophage.v1alpha2.DocumentService",
                        input=bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentRequest,
                        output=bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_document,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.v1alpha2.DocumentService"


class DocumentServiceClient(ConnectClient):
    async def store_document(
        self,
        request: bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StoreDocument",
                service_name="bibliophage.v1alpha2.DocumentService",
                input=bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentRequest,
                output=bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_document(
        self,
        request: bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDocument",
                service_name="bibliophage.v1alpha2.DocumentService",
                input=bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentRequest,
                output=bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_document(
        self,
        request: bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateDocument",
                service_name="bibliophage.v1alpha2.DocumentService",
                input=bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentRequest,
                output=bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def search_documents(
        self,
        request: bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SearchDocuments",
                service_name="bibliophage.v1alpha2.DocumentService",
                input=bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsRequest,
                output=bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_document(
        self,
        request: bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteDocument",
                service_name="bibliophage.v1alpha2.DocumentService",
                input=bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentRequest,
                output=bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class DocumentServiceSync(Protocol):
    def store_document(self, request: bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_document(self, request: bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_document(self, request: bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def search_documents(self, request: bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_document(self, request: bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DocumentServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: DocumentServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/bibliophage.v1alpha2.DocumentService/StoreDocument": EndpointSync.unary(
                    method=MethodInfo(
                        name="StoreDocument",
                        service_name="bibliophage.v1alpha2.DocumentService",
                        input=bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentRequest,
                        output=bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.store_document,
                ),
                "/bibliophage.v1alpha2.DocumentService/GetDocument": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDocument",
                        service_name="bibliophage.v1alpha2.DocumentService",
                        input=bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentRequest,
                        output=bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_document,
                ),
                "/bibliophage.v1alpha2.DocumentService/UpdateDocument": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateDocument",
                        service_name="bibliophage.v1alpha2.DocumentService",
                        input=bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentRequest,
                        output=bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_document,
                ),
                "/bibliophage.v1alpha2.DocumentService/SearchDocuments": EndpointSync.unary(
                    method=MethodInfo(
                        name="SearchDocuments",
                        service_name="bibliophage.v1alpha2.DocumentService",
                        input=bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsRequest,
                        output=bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.search_documents,
                ),
                "/bibliophage.v1alpha2.DocumentService/DeleteDocument": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteDocument",
                        service_name="bibliophage.v1alpha2.DocumentService",
                        input=bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentRequest,
                        output=bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_document,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.v1alpha2.DocumentService"


class DocumentServiceClientSync(ConnectClientSync):
    def store_document(
        self,
        request: bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StoreDocument",
                service_name="bibliophage.v1alpha2.DocumentService",
                input=bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentRequest,
                output=bibliophage_dot_v1alpha2_dot_document__pb2.StoreDocumentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_document(
        self,
        request: bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDocument",
                service_name="bibliophage.v1alpha2.DocumentService",
                input=bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentRequest,
                output=bibliophage_dot_v1alpha2_dot_document__pb2.GetDocumentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_document(
        self,
        request: bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateDocument",
                service_name="bibliophage.v1alpha2.DocumentService",
                input=bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentRequest,
                output=bibliophage_dot_v1alpha2_dot_document__pb2.UpdateDocumentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def search_documents(
        self,
        request: bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SearchDocuments",
                service_name="bibliophage.v1alpha2.DocumentService",
                input=bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsRequest,
                output=bibliophage_dot_v1alpha2_dot_document__pb2.SearchDocumentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_document(
        self,
        request: bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteDocument",
                service_name="bibliophage.v1alpha2.DocumentService",
                input=bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentRequest,
                output=bibliophage_dot_v1alpha2_dot_document__pb2.DeleteDocumentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
