import logging
import traceback
import uuid
from datetime import datetime, timezone

from google.protobuf import timestamp_pb2

import bibliophage.v1alpha3.pdf_pb2 as pdf_api
import bibliophage.v1alpha3.document_pb2 as doc_api
from config import get_settings
from database import get_database
from docling_pipeline import DoclingPipeline

logger = logging.getLogger(__name__)


class LoadingServiceImplementation:
    """
    Loading service implementation using Docling for PDF processing.

    This service processes PDFs using docling's batch-based pipeline and stores
    them as Documents in the unified documents collection. The LoadPdf RPC
    returns PDF-specific metadata for compatibility with the PDF upload workflow,
    but the data is stored as a Document internally.
    """

    def __init__(self):
        """Initialise the loading service with configuration from environment variables."""
        settings = get_settings()

        self.db = get_database()

        # Initialise docling pipeline
        # TODO: Make these configurable via environment variables or request parameters
        self.docling_pipeline = DoclingPipeline(
            ocr_batch_size=4,
            layout_batch_size=64,
            table_batch_size=4,
            do_ocr=False,
        )

        logger.info(
            "Loading service initialised with Docling pipeline and database repository"
        )

    async def load_pdf(self, request: pdf_api.LoadPdfRequest, ctx):
        """
        Load a PDF using docling's batch processing pipeline.

        This method:
        1. Validates the request
        2. Processes PDF using the Docling pipeline
        3. Stores the result as a Document in the unified documents collection
        4. Returns LoadPdfResponse with PDF metadata

        Args:
            request: LoadPdfRequest containing PDF metadata and file data
            ctx: gRPC context (passed because the autogenerated API demands it
            besides, we might want to do stuff with the request context later)

        Returns:
            LoadPdfResponse with stored document metadata
        """
        try:
            logger.info(f"Received LoadPdf request for file: {request.pdf.name}")

            # Validate systems array (must have at least one value)
            if not request.pdf.systems:
                return pdf_api.LoadPdfResponse(
                    success=False,
                    message="PDF must belong to at least one system",
                )

            pdf_bytes = request.file_data

            # Process PDF using Docling pipeline
            logger.info("Processing PDF with Docling pipeline...")
            processing_result = self.docling_pipeline.process_pdf(
                pdf_bytes=pdf_bytes,
                pdf_name=request.pdf.name,
                use_smart_batching=True,
                memory_per_page_mb=67.8,  # TODO: Make configurable
            )

            logger.info(
                f"PDF processing complete: {processing_result['successful_batches']}/{len(processing_result['processed_batches'])} batches succeeded"
            )

            # Store as Document in unified documents collection
            document_id = str(uuid.uuid4())
            now = datetime.now(timezone.utc)

            # Convert protobuf tags to dict format for database storage
            tags = []
            for tag in request.pdf.tags:
                tags.append({"name": tag.name, "values": list(tag.values)})

            # Determine DocumentType based on PDF type
            # Map PDF type strings to DocumentType enums
            pdf_type_upper = request.pdf.type.upper()
            if "RULEBOOK" in pdf_type_upper or "CORE" in pdf_type_upper:
                doc_type = "RULEBOOK"
                source_type = "CORE"
            elif "SUPPLEMENT" in pdf_type_upper or "EXPANSION" in pdf_type_upper:
                doc_type = "EXPANSION"
                source_type = "SUPPLEMENT"
            elif "ADVENTURE" in pdf_type_upper:
                doc_type = "ADVENTURE"
                source_type = "SUPPLEMENT"
            elif "BESTIARY" in pdf_type_upper or "MONSTER" in pdf_type_upper:
                doc_type = "BESTIARY"
                source_type = "SUPPLEMENT"
            else:
                doc_type = "RULEBOOK"
                source_type = "CORE"

            # TODO: Track vector_chunk_count when vector embedding is implemented
            vector_chunk_count = 0

            # Create metadata for PDF-sourced document
            metadata = {
                "file_sise": len(pdf_bytes),
                "publication_type": request.pdf.type,
                "pdf": {
                    "loading_batch_count": len(processing_result["processed_batches"]),
                    "vector_chunk_count": vector_chunk_count,
                    "page_count": processing_result["total_pages"],
                },
            }

            await self.db.store_document(
                document_id=document_id,
                name=request.pdf.name,
                systems=list(request.pdf.systems),
                source_type=source_type,
                content=processing_result["content"],
                doc_type=doc_type,
                tags=tags,
                created_at=now,
                metadata=metadata,
            )

            # Create response with PDF metadata (for API compatibility)
            stored_pdf = pdf_api.Pdf()
            stored_pdf.CopyFrom(request.pdf)
            stored_pdf.id = document_id
            stored_pdf.page_count = processing_result["total_pages"]
            stored_pdf.batch_count = len(processing_result["processed_batches"])
            stored_pdf.vector_chunk_count = vector_chunk_count
            stored_pdf.file_size = len(pdf_bytes)

            # Set timestamps
            timestamp = timestamp_pb2.Timestamp()
            timestamp.FromDatetime(now)
            stored_pdf.created_at.CopyFrom(timestamp)
            stored_pdf.updated_at.CopyFrom(timestamp)

            return pdf_api.LoadPdfResponse(
                success=True,
                message=f"PDF {request.pdf.name} processed successfully ({processing_result['successful_batches']}/{len(processing_result['processed_batches'])} batches)",
                pdf=stored_pdf,
            )

        except Exception as e:
            logger.error(f"Exception in load_pdf: {e}\n{traceback.format_exc()}")
            raise

    async def search_pdfs(
        self,
        request: pdf_api.SearchPdfsRequest,
        ctx,
    ) -> pdf_api.SearchPdfsResponse:
        """Search for PDFs in the unified documents collection.

        This method delegates to the documents collection but filters for
        PDF-sourced documents (those with metadata.pdf field).
        """

        logger.info("Received SearchPdfsRequest")

        try:
            # Convert tag filters from protobuf to database format
            tag_filters = None
            if request.tag_filters:
                tag_filters = []
                for tag_filter in request.tag_filters:
                    tag_filters.append(
                        {
                            "name": tag_filter.name,
                            "value": tag_filter.value,
                        }
                    )

            # Extract system filters
            system_filters = (
                list(request.system_filters) if request.system_filters else None
            )

            # Search documents collection
            documents, total_count = await self.db.search_documents(
                name_query=request.title_query
                if request.HasField("title_query")
                else None,
                system_filters=system_filters,
                type_filter=request.type_filter
                if request.HasField("type_filter")
                else None,
                tag_filters=tag_filters,
                page_size=request.page_size if request.page_size > 0 else 50,
                page_number=request.page_number if request.page_number >= 0 else 0,
            )

            # Filter to only include PDF-sourced documents (those with metadata.pdf)
            pdf_documents = [
                doc
                for doc in documents
                if "metadata" in doc and "pdf" in doc.get("metadata", {})
            ]

            # Convert database documents to PdfListItem protobuf objects
            found_pdfs = []
            for doc in pdf_documents:
                pdf_item = pdf_api.PdfListItem(
                    id=doc.get("_id", ""),
                    name=doc.get("name", ""),
                    type=doc.get("metadata", {}).get("publication_type", ""),
                    page_count=doc.get("metadata", {})
                    .get("pdf", {})
                    .get("page_count", 0),
                    file_size=doc.get("metadata", {}).get("file_size", 0),
                    batch_count=doc.get("metadata", {})
                    .get("pdf", {})
                    .get("loading_batch_count", 0),
                    vector_chunk_count=doc.get("metadata", {})
                    .get("pdf", {})
                    .get("vector_chunk_count", 0),
                )

                # Add systems array
                pdf_item.systems.extend(doc.get("systems", []))

                # Handle timestamps
                if "created_at" in doc:
                    created_ts = timestamp_pb2.Timestamp()
                    created_ts.FromDatetime(doc["created_at"])
                    pdf_item.created_at.CopyFrom(created_ts)

                if "updated_at" in doc:
                    updated_ts = timestamp_pb2.Timestamp()
                    updated_ts.FromDatetime(doc["updated_at"])
                    pdf_item.updated_at.CopyFrom(updated_ts)

                # Add tags
                for tag_data in doc.get("tags", []):
                    tag = pdf_api.Tag()
                    tag.name = tag_data.get("name", "")
                    tag.values.extend(tag_data.get("values", []))
                    pdf_item.tags.append(tag)

                found_pdfs.append(pdf_item)

            # Calculate pagination
            pdf_count = len(pdf_documents)
            page_number = request.page_number if request.page_number >= 0 else 0
            page_size = request.page_size if request.page_size > 0 else 50
            has_more = (page_number + 1) * page_size < pdf_count

            return pdf_api.SearchPdfsResponse(
                success=True,
                message="Search successful",
                pdfs=found_pdfs,
                total_count=pdf_count,
                page_number=page_number,
                has_more=has_more,
            )
        except Exception as e:
            exception_message = f"{type(e).__name__} occurred during PDF search: {e}"
            logger.error(exception_message)
            logger.error(traceback.format_exc())

            return pdf_api.SearchPdfsResponse(
                success=False,
                message=exception_message,
                pdfs=[],
                total_count=0,
                page_number=request.page_number if request.page_number >= 0 else 0,
                has_more=False,
            )

    async def get_pdf(
        self,
        request: pdf_api.GetPdfRequest,
        ctx,
    ) -> pdf_api.GetPdfResponse:
        """
        Retrieve a specific PDF by ID from the documents collection.

        This queries the unified documents collection and returns the document
        as a Pdf message if it has PDF metadata.
        """
        logger.info(f"Received GetPdfRequest for ID: {request.id}")

        try:
            # Fetch document from database
            doc = await self.db.get_document_by_id(request.id)

            if not doc:
                return pdf_api.GetPdfResponse(
                    success=False,
                    message=f"PDF with ID '{request.id}' not found",
                )

            # Verify this is a PDF-sourced document
            if "metadata" not in doc or "pdf" not in doc.get("metadata", {}):
                return pdf_api.GetPdfResponse(
                    success=False,
                    message=f"Document with ID '{request.id}' is not a PDF",
                )

            # Convert database document to protobuf Pdf message
            pdf = pdf_api.Pdf(
                id=doc.get("_id", ""),
                name=doc.get("name", ""),
                type=doc.get("metadata", {}).get("publication_type", ""),
                page_count=doc.get("metadata", {}).get("pdf", {}).get("page_count", 0),
                file_size=doc.get("metadata", {}).get("file_size", 0),
                batch_count=doc.get("metadata", {})
                .get("pdf", {})
                .get("loading_batch_count", 0),
                vector_chunk_count=doc.get("metadata", {})
                .get("pdf", {})
                .get("vector_chunk_count", 0),
            )

            # Add systems array
            pdf.systems.extend(doc.get("systems", []))

            # Handle timestamps
            if "created_at" in doc:
                created_ts = timestamp_pb2.Timestamp()
                created_ts.FromDatetime(doc["created_at"])
                pdf.created_at.CopyFrom(created_ts)

            if "updated_at" in doc:
                updated_ts = timestamp_pb2.Timestamp()
                updated_ts.FromDatetime(doc["updated_at"])
                pdf.updated_at.CopyFrom(updated_ts)

            # Handle tags
            for tag_data in doc.get("tags", []):
                tag = pdf_api.Tag()
                tag.name = tag_data.get("name", "")
                tag.values.extend(tag_data.get("values", []))
                pdf.tags.append(tag)

            # Include markdown content if present
            if "content" in doc:
                pdf.content = doc["content"]
                logger.info(f"Included {len(pdf.content)} characters of content")

            logger.info(f"Successfully retrieved PDF: {pdf.name} ({pdf.id})")
            return pdf_api.GetPdfResponse(
                success=True,
                message=f"PDF '{pdf.name}' retrieved successfully",
                pdf=pdf,
            )

        except Exception as e:
            logger.error(f"Error retrieving PDF: {e}")
            logger.error(traceback.format_exc())
            return pdf_api.GetPdfResponse(
                success=False,
                message=f"Error retrieving PDF: {str(e)}",
            )
