import logging
import traceback
import uuid
from datetime import UTC, datetime

from google.protobuf import timestamp_pb2

import bibliophage.v1alpha3.pdf_pb2 as pdf_api
from config import get_settings
from postgres_db import get_postgres_db
from docling_pipeline import DoclingPipeline

logger = logging.getLogger(__name__)


class LoadingServiceImplementation:
    """Loading service implementation using Docling for PDF processing.

    This service processes PDFs using docling's batch-based pipeline and stores
    them as Documents in the unified documents collection. The LoadPdf RPC
    returns PDF-specific metadata for compatibility with the PDF upload workflow,
    but the data is stored as a Document internally.
    """

    def __init__(self):
        """Initialise the loading service with configuration from environment variables."""
        settings = get_settings()

        self.db = get_postgres_db()

        # Initialise docling pipeline
        # TODO: Make these configurable via environment variables or request parameters
        self.docling_pipeline = DoclingPipeline(
            ocr_batch_size=4,
            layout_batch_size=64,
            table_batch_size=4,
            do_ocr=False,
        )

        logger.info(
            "Loading service initialised with Docling pipeline and database repository",
        )

    async def load_pdf(self, request: pdf_api.LoadPdfRequest, ctx):
        """Load a PDF using docling's batch processing pipeline.

        This method:
        1. Validates the request
        2. Processes PDF using the Docling pipeline
        3. Stores the result as a Document in the unified documents collection
        4. Returns LoadPdfResponse with PDF metadata

        Args:
            request: LoadPdfRequest containing PDF metadata and file data
            ctx: gRPC context (passed because the autogenerated API demands it
            besides, we might want to do stuff with the request context later)

        Returns:
            LoadPdfResponse with stored document metadata

        """
        try:
            logger.info(f"Received LoadPdf request for file: {request.pdf.name}")

            # Validate systems array (must have at least one value)
            if not request.pdf.systems:
                return pdf_api.LoadPdfResponse(
                    success=False,
                    message="PDF must belong to at least one system",
                )

            pdf_bytes = request.file_data

            # Process PDF using Docling pipeline
            logger.info("Processing PDF with Docling pipeline...")
            processing_result = self.docling_pipeline.process_pdf(
                pdf_bytes=pdf_bytes,
                pdf_name=request.pdf.name,
                use_smart_batching=True,
                memory_per_page_mb=67.8,  # TODO: Make configurable
            )

            logger.info(
                f"PDF processing complete: {processing_result['successful_batches']}/{len(processing_result['processed_batches'])} batches succeeded",
            )

            # Store as Document in unified documents collection
            document_id = str(uuid.uuid4())
            now = datetime.now(UTC)

            # Convert protobuf tags to dict format for database storage
            tags = []
            for tag in request.pdf.tags:
                tags.append({"name": tag.name, "values": list(tag.values)})

            # Determine DocumentType based on PDF type
            # Map PDF type strings to DocumentType enums
            pdf_type_upper = request.pdf.type.upper()
            if "RULEBOOK" in pdf_type_upper or "CORE" in pdf_type_upper:
                doc_type = "RULEBOOK"
                source_type = "CORE"
            elif "SUPPLEMENT" in pdf_type_upper or "EXPANSION" in pdf_type_upper:
                doc_type = "EXPANSION"
                source_type = "SUPPLEMENT"
            elif "ADVENTURE" in pdf_type_upper:
                doc_type = "ADVENTURE"
                source_type = "SUPPLEMENT"
            elif "BESTIARY" in pdf_type_upper or "MONSTER" in pdf_type_upper:
                doc_type = "BESTIARY"
                source_type = "SUPPLEMENT"
            else:
                doc_type = "RULEBOOK"
                source_type = "CORE"

            # TODO: Track vector_chunk_count when vector embedding is implemented
            vector_chunk_count = 0

            # Create metadata for PDF-sourced document
            metadata = {
                "file_sise": len(pdf_bytes),
                "publication_type": request.pdf.type,
                "pdf": {
                    "loading_batch_count": len(processing_result["processed_batches"]),
                    "vector_chunk_count": vector_chunk_count,
                    "page_count": processing_result["total_pages"],
                },
            }

            await self.db.store_document(
                document_id=document_id,
                name=request.pdf.name,
                systems=list(request.pdf.systems),
                source_type=source_type,
                content=processing_result["content"],
                doc_type=doc_type,
                tags=tags,
                created_at=now,
                metadata=metadata,
            )

            # Create response with PDF metadata (for API compatibility)
            stored_pdf = pdf_api.Pdf()
            stored_pdf.CopyFrom(request.pdf)
            stored_pdf.id = document_id
            stored_pdf.page_count = processing_result["total_pages"]
            stored_pdf.batch_count = len(processing_result["processed_batches"])
            stored_pdf.vector_chunk_count = vector_chunk_count
            stored_pdf.file_size = len(pdf_bytes)

            # Set timestamps
            timestamp = timestamp_pb2.Timestamp()
            timestamp.FromDatetime(now)
            stored_pdf.created_at.CopyFrom(timestamp)
            stored_pdf.updated_at.CopyFrom(timestamp)

            return pdf_api.LoadPdfResponse(
                success=True,
                message=f"PDF {request.pdf.name} processed successfully ({processing_result['successful_batches']}/{len(processing_result['processed_batches'])} batches)",
                pdf=stored_pdf,
            )

        except Exception as e:
            logger.error(f"Exception in load_pdf: {e}\n{traceback.format_exc()}")
            raise
