// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: bibliophage/v1alpha3/graph.proto

package bibliophage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node represents a vertex in the knowledge graph
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier (assigned by the system)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type identifier (e.g., "character", "location", "document")
	// References a TypeDefinition
	TypeId string `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	// Dynamic properties validated against the type's schema
	// Struct works like JSON
	Properties    *structpb.Struct `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_bibliophage_v1alpha3_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *Node) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Edge represents a relationship between two nodes
type Edge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier (assigned by the system)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Relationship type (e.g., "located_in", "knows", "owns")
	Relationship string `protobuf:"bytes,2,opt,name=relationship,proto3" json:"relationship,omitempty"`
	// Whether this edge has a direction (A → B vs A — B)
	Directed bool `protobuf:"varint,3,opt,name=directed,proto3" json:"directed,omitempty"`
	// Source node ID (or "node A" for undirected edges)
	NodeA string `protobuf:"bytes,4,opt,name=node_a,json=nodeA,proto3" json:"node_a,omitempty"`
	// Target node ID (or "node B" for undirected edges)
	NodeB         string `protobuf:"bytes,5,opt,name=node_b,json=nodeB,proto3" json:"node_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_bibliophage_v1alpha3_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Edge) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *Edge) GetDirected() bool {
	if x != nil {
		return x.Directed
	}
	return false
}

func (x *Edge) GetNodeA() string {
	if x != nil {
		return x.NodeA
	}
	return ""
}

func (x *Edge) GetNodeB() string {
	if x != nil {
		return x.NodeB
	}
	return ""
}

type CreateNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type identifier for this node
	TypeId string `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	// Properties for this node (validated against type schema)
	Properties    *structpb.Struct `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_bibliophage_v1alpha3_graph_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNodeRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *CreateNodeRequest) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type CreateNodeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The created node with assigned ID
	Node          *Node `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeResponse) Reset() {
	*x = CreateNodeResponse{}
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeResponse) ProtoMessage() {}

func (x *CreateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeResponse) Descriptor() ([]byte, []int) {
	return file_bibliophage_v1alpha3_graph_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type CreateEdgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relationship type (e.g., "located_in", "member_of")
	Relationship string `protobuf:"bytes,1,opt,name=relationship,proto3" json:"relationship,omitempty"`
	// Whether this edge is directed
	Directed bool `protobuf:"varint,2,opt,name=directed,proto3" json:"directed,omitempty"`
	// Source node ID
	SourceNodeId string `protobuf:"bytes,3,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	// Target node ID
	TargetNodeId  string `protobuf:"bytes,4,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgeRequest) Reset() {
	*x = CreateEdgeRequest{}
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeRequest) ProtoMessage() {}

func (x *CreateEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeRequest.ProtoReflect.Descriptor instead.
func (*CreateEdgeRequest) Descriptor() ([]byte, []int) {
	return file_bibliophage_v1alpha3_graph_proto_rawDescGZIP(), []int{4}
}

func (x *CreateEdgeRequest) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *CreateEdgeRequest) GetDirected() bool {
	if x != nil {
		return x.Directed
	}
	return false
}

func (x *CreateEdgeRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *CreateEdgeRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type CreateEdgeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The created edge with assigned ID
	Edge          *Edge `protobuf:"bytes,3,opt,name=edge,proto3" json:"edge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgeResponse) Reset() {
	*x = CreateEdgeResponse{}
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeResponse) ProtoMessage() {}

func (x *CreateEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeResponse.ProtoReflect.Descriptor instead.
func (*CreateEdgeResponse) Descriptor() ([]byte, []int) {
	return file_bibliophage_v1alpha3_graph_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEdgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateEdgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateEdgeResponse) GetEdge() *Edge {
	if x != nil {
		return x.Edge
	}
	return nil
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_bibliophage_v1alpha3_graph_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeResponse) Reset() {
	*x = DeleteNodeResponse{}
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeResponse) ProtoMessage() {}

func (x *DeleteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) {
	return file_bibliophage_v1alpha3_graph_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEdgeRequest) Reset() {
	*x = DeleteEdgeRequest{}
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEdgeRequest) ProtoMessage() {}

func (x *DeleteEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEdgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEdgeRequest) Descriptor() ([]byte, []int) {
	return file_bibliophage_v1alpha3_graph_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEdgeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEdgeResponse) Reset() {
	*x = DeleteEdgeResponse{}
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEdgeResponse) ProtoMessage() {}

func (x *DeleteEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bibliophage_v1alpha3_graph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEdgeResponse.ProtoReflect.Descriptor instead.
func (*DeleteEdgeResponse) Descriptor() ([]byte, []int) {
	return file_bibliophage_v1alpha3_graph_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteEdgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteEdgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bibliophage_v1alpha3_graph_proto protoreflect.FileDescriptor

const file_bibliophage_v1alpha3_graph_proto_rawDesc = "" +
	"\n" +
	" bibliophage/v1alpha3/graph.proto\x12\x14bibliophage.v1alpha3\x1a\x1cgoogle/protobuf/struct.proto\"h\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\tR\x06typeId\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"\x84\x01\n" +
	"\x04Edge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\frelationship\x18\x02 \x01(\tR\frelationship\x12\x1a\n" +
	"\bdirected\x18\x03 \x01(\bR\bdirected\x12\x15\n" +
	"\x06node_a\x18\x04 \x01(\tR\x05nodeA\x12\x15\n" +
	"\x06node_b\x18\x05 \x01(\tR\x05nodeB\"e\n" +
	"\x11CreateNodeRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x127\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"x\n" +
	"\x12CreateNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04node\x18\x03 \x01(\v2\x1a.bibliophage.v1alpha3.NodeR\x04node\"\x9f\x01\n" +
	"\x11CreateEdgeRequest\x12\"\n" +
	"\frelationship\x18\x01 \x01(\tR\frelationship\x12\x1a\n" +
	"\bdirected\x18\x02 \x01(\bR\bdirected\x12$\n" +
	"\x0esource_node_id\x18\x03 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x04 \x01(\tR\ftargetNodeId\"x\n" +
	"\x12CreateEdgeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04edge\x18\x03 \x01(\v2\x1a.bibliophage.v1alpha3.EdgeR\x04edge\"#\n" +
	"\x11DeleteNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x12DeleteNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\x11DeleteEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x12DeleteEdgeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x92\x03\n" +
	"\fGraphService\x12_\n" +
	"\n" +
	"CreateNode\x12'.bibliophage.v1alpha3.CreateNodeRequest\x1a(.bibliophage.v1alpha3.CreateNodeResponse\x12_\n" +
	"\n" +
	"CreateEdge\x12'.bibliophage.v1alpha3.CreateEdgeRequest\x1a(.bibliophage.v1alpha3.CreateEdgeResponse\x12_\n" +
	"\n" +
	"DeleteNode\x12'.bibliophage.v1alpha3.DeleteNodeRequest\x1a(.bibliophage.v1alpha3.DeleteNodeResponse\x12_\n" +
	"\n" +
	"DeleteEdge\x12'.bibliophage.v1alpha3.DeleteEdgeRequest\x1a(.bibliophage.v1alpha3.DeleteEdgeResponseb\x06proto3"

var (
	file_bibliophage_v1alpha3_graph_proto_rawDescOnce sync.Once
	file_bibliophage_v1alpha3_graph_proto_rawDescData []byte
)

func file_bibliophage_v1alpha3_graph_proto_rawDescGZIP() []byte {
	file_bibliophage_v1alpha3_graph_proto_rawDescOnce.Do(func() {
		file_bibliophage_v1alpha3_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bibliophage_v1alpha3_graph_proto_rawDesc), len(file_bibliophage_v1alpha3_graph_proto_rawDesc)))
	})
	return file_bibliophage_v1alpha3_graph_proto_rawDescData
}

var file_bibliophage_v1alpha3_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bibliophage_v1alpha3_graph_proto_goTypes = []any{
	(*Node)(nil),               // 0: bibliophage.v1alpha3.Node
	(*Edge)(nil),               // 1: bibliophage.v1alpha3.Edge
	(*CreateNodeRequest)(nil),  // 2: bibliophage.v1alpha3.CreateNodeRequest
	(*CreateNodeResponse)(nil), // 3: bibliophage.v1alpha3.CreateNodeResponse
	(*CreateEdgeRequest)(nil),  // 4: bibliophage.v1alpha3.CreateEdgeRequest
	(*CreateEdgeResponse)(nil), // 5: bibliophage.v1alpha3.CreateEdgeResponse
	(*DeleteNodeRequest)(nil),  // 6: bibliophage.v1alpha3.DeleteNodeRequest
	(*DeleteNodeResponse)(nil), // 7: bibliophage.v1alpha3.DeleteNodeResponse
	(*DeleteEdgeRequest)(nil),  // 8: bibliophage.v1alpha3.DeleteEdgeRequest
	(*DeleteEdgeResponse)(nil), // 9: bibliophage.v1alpha3.DeleteEdgeResponse
	(*structpb.Struct)(nil),    // 10: google.protobuf.Struct
}
var file_bibliophage_v1alpha3_graph_proto_depIdxs = []int32{
	10, // 0: bibliophage.v1alpha3.Node.properties:type_name -> google.protobuf.Struct
	10, // 1: bibliophage.v1alpha3.CreateNodeRequest.properties:type_name -> google.protobuf.Struct
	0,  // 2: bibliophage.v1alpha3.CreateNodeResponse.node:type_name -> bibliophage.v1alpha3.Node
	1,  // 3: bibliophage.v1alpha3.CreateEdgeResponse.edge:type_name -> bibliophage.v1alpha3.Edge
	2,  // 4: bibliophage.v1alpha3.GraphService.CreateNode:input_type -> bibliophage.v1alpha3.CreateNodeRequest
	4,  // 5: bibliophage.v1alpha3.GraphService.CreateEdge:input_type -> bibliophage.v1alpha3.CreateEdgeRequest
	6,  // 6: bibliophage.v1alpha3.GraphService.DeleteNode:input_type -> bibliophage.v1alpha3.DeleteNodeRequest
	8,  // 7: bibliophage.v1alpha3.GraphService.DeleteEdge:input_type -> bibliophage.v1alpha3.DeleteEdgeRequest
	3,  // 8: bibliophage.v1alpha3.GraphService.CreateNode:output_type -> bibliophage.v1alpha3.CreateNodeResponse
	5,  // 9: bibliophage.v1alpha3.GraphService.CreateEdge:output_type -> bibliophage.v1alpha3.CreateEdgeResponse
	7,  // 10: bibliophage.v1alpha3.GraphService.DeleteNode:output_type -> bibliophage.v1alpha3.DeleteNodeResponse
	9,  // 11: bibliophage.v1alpha3.GraphService.DeleteEdge:output_type -> bibliophage.v1alpha3.DeleteEdgeResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_bibliophage_v1alpha3_graph_proto_init() }
func file_bibliophage_v1alpha3_graph_proto_init() {
	if File_bibliophage_v1alpha3_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bibliophage_v1alpha3_graph_proto_rawDesc), len(file_bibliophage_v1alpha3_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bibliophage_v1alpha3_graph_proto_goTypes,
		DependencyIndexes: file_bibliophage_v1alpha3_graph_proto_depIdxs,
		MessageInfos:      file_bibliophage_v1alpha3_graph_proto_msgTypes,
	}.Build()
	File_bibliophage_v1alpha3_graph_proto = out.File
	file_bibliophage_v1alpha3_graph_proto_goTypes = nil
	file_bibliophage_v1alpha3_graph_proto_depIdxs = nil
}
