# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: bibliophage/v1alpha3/graph.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import bibliophage.v1alpha3.graph_pb2 as bibliophage_dot_v1alpha3_dot_graph__pb2


class GraphService(Protocol):
    async def create_node(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_edge(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_node(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_edge(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_neighbours(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_edges(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class GraphServiceASGIApplication(ConnectASGIApplication[GraphService]):
    def __init__(self, service: GraphService | AsyncGenerator[GraphService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/bibliophage.v1alpha3.GraphService/CreateNode": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateNode",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_node,
                ),
                "/bibliophage.v1alpha3.GraphService/CreateEdge": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateEdge",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_edge,
                ),
                "/bibliophage.v1alpha3.GraphService/DeleteNode": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteNode",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_node,
                ),
                "/bibliophage.v1alpha3.GraphService/DeleteEdge": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteEdge",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_edge,
                ),
                "/bibliophage.v1alpha3.GraphService/GetNeighbours": Endpoint.unary(
                    method=MethodInfo(
                        name="GetNeighbours",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_neighbours,
                ),
                "/bibliophage.v1alpha3.GraphService/ListEdges": Endpoint.unary(
                    method=MethodInfo(
                        name="ListEdges",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_edges,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.v1alpha3.GraphService"


class GraphServiceClient(ConnectClient):
    async def create_node(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateNode",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_edge(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateEdge",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_node(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteNode",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_edge(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteEdge",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_neighbours(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNeighbours",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_edges(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEdges",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class GraphServiceSync(Protocol):
    def create_node(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_edge(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_node(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_edge(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_neighbours(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_edges(self, request: bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class GraphServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: GraphServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/bibliophage.v1alpha3.GraphService/CreateNode": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateNode",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_node,
                ),
                "/bibliophage.v1alpha3.GraphService/CreateEdge": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateEdge",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_edge,
                ),
                "/bibliophage.v1alpha3.GraphService/DeleteNode": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteNode",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_node,
                ),
                "/bibliophage.v1alpha3.GraphService/DeleteEdge": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteEdge",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_edge,
                ),
                "/bibliophage.v1alpha3.GraphService/GetNeighbours": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetNeighbours",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_neighbours,
                ),
                "/bibliophage.v1alpha3.GraphService/ListEdges": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListEdges",
                        service_name="bibliophage.v1alpha3.GraphService",
                        input=bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesRequest,
                        output=bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_edges,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.v1alpha3.GraphService"


class GraphServiceClientSync(ConnectClientSync):
    def create_node(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateNode",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateNodeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_edge(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateEdge",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.CreateEdgeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_node(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteNode",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteNodeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_edge(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteEdge",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.DeleteEdgeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_neighbours(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNeighbours",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.GetNeighboursResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_edges(
        self,
        request: bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEdges",
                service_name="bibliophage.v1alpha3.GraphService",
                input=bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesRequest,
                output=bibliophage_dot_v1alpha3_dot_graph__pb2.ListEdgesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
