# yarn's Plug and Play does not work well with code that wants to import other code at build time
# https://yarnpkg.com/configuration/yarnrc#nodeLinker
# pnpm seems to be a middle ground between pnp and old fashioned node_imports
# however, it still broke when being used across filesystems
# nodeLinker: pnpm
# hence, we are back to the old fashioned stuff for now
nodeLinker: node-modules

# the other modes use hardlinks which do not work across filesystems
# https://yarnpkg.com/configuration/yarnrc#nmMode
nmMode: classic
