//
// Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: arcadedb-server.proto

package arcadedb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArcadeDbService_StreamQuery_FullMethodName         = "/com.arcadedb.grpc.ArcadeDbService/StreamQuery"
	ArcadeDbService_ExecuteCommand_FullMethodName      = "/com.arcadedb.grpc.ArcadeDbService/ExecuteCommand"
	ArcadeDbService_ExecuteQuery_FullMethodName        = "/com.arcadedb.grpc.ArcadeDbService/ExecuteQuery"
	ArcadeDbService_CreateRecord_FullMethodName        = "/com.arcadedb.grpc.ArcadeDbService/CreateRecord"
	ArcadeDbService_UpdateRecord_FullMethodName        = "/com.arcadedb.grpc.ArcadeDbService/UpdateRecord"
	ArcadeDbService_LookupByRid_FullMethodName         = "/com.arcadedb.grpc.ArcadeDbService/LookupByRid"
	ArcadeDbService_DeleteRecord_FullMethodName        = "/com.arcadedb.grpc.ArcadeDbService/DeleteRecord"
	ArcadeDbService_BulkInsert_FullMethodName          = "/com.arcadedb.grpc.ArcadeDbService/BulkInsert"
	ArcadeDbService_InsertStream_FullMethodName        = "/com.arcadedb.grpc.ArcadeDbService/InsertStream"
	ArcadeDbService_InsertBidirectional_FullMethodName = "/com.arcadedb.grpc.ArcadeDbService/InsertBidirectional"
	ArcadeDbService_BeginTransaction_FullMethodName    = "/com.arcadedb.grpc.ArcadeDbService/BeginTransaction"
	ArcadeDbService_CommitTransaction_FullMethodName   = "/com.arcadedb.grpc.ArcadeDbService/CommitTransaction"
	ArcadeDbService_RollbackTransaction_FullMethodName = "/com.arcadedb.grpc.ArcadeDbService/RollbackTransaction"
)

// ArcadeDbServiceClient is the client API for ArcadeDbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArcadeDbServiceClient interface {
	// Streaming queries
	StreamQuery(ctx context.Context, in *StreamQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult], error)
	// Execute arbitrary command (INSERT/UPDATE/DDL/etc.)
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error)
	// Single-record helpers
	CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*CreateRecordResponse, error)
	UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*UpdateRecordResponse, error)
	LookupByRid(ctx context.Context, in *LookupByRidRequest, opts ...grpc.CallOption) (*LookupByRidResponse, error)
	DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error)
	// Insert APIs (unary, client-streaming, and bidi)
	BulkInsert(ctx context.Context, in *BulkInsertRequest, opts ...grpc.CallOption) (*InsertSummary, error)
	InsertStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InsertChunk, InsertSummary], error)
	InsertBidirectional(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InsertRequest, InsertResponse], error)
	// Transaction operations
	BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error)
	CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*CommitTransactionResponse, error)
	RollbackTransaction(ctx context.Context, in *RollbackTransactionRequest, opts ...grpc.CallOption) (*RollbackTransactionResponse, error)
}

type arcadeDbServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArcadeDbServiceClient(cc grpc.ClientConnInterface) ArcadeDbServiceClient {
	return &arcadeDbServiceClient{cc}
}

func (c *arcadeDbServiceClient) StreamQuery(ctx context.Context, in *StreamQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArcadeDbService_ServiceDesc.Streams[0], ArcadeDbService_StreamQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamQueryRequest, QueryResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArcadeDbService_StreamQueryClient = grpc.ServerStreamingClient[QueryResult]

func (c *arcadeDbServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, ArcadeDbService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbServiceClient) ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteQueryResponse)
	err := c.cc.Invoke(ctx, ArcadeDbService_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbServiceClient) CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*CreateRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRecordResponse)
	err := c.cc.Invoke(ctx, ArcadeDbService_CreateRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbServiceClient) UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*UpdateRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRecordResponse)
	err := c.cc.Invoke(ctx, ArcadeDbService_UpdateRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbServiceClient) LookupByRid(ctx context.Context, in *LookupByRidRequest, opts ...grpc.CallOption) (*LookupByRidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupByRidResponse)
	err := c.cc.Invoke(ctx, ArcadeDbService_LookupByRid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbServiceClient) DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRecordResponse)
	err := c.cc.Invoke(ctx, ArcadeDbService_DeleteRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbServiceClient) BulkInsert(ctx context.Context, in *BulkInsertRequest, opts ...grpc.CallOption) (*InsertSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertSummary)
	err := c.cc.Invoke(ctx, ArcadeDbService_BulkInsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbServiceClient) InsertStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InsertChunk, InsertSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArcadeDbService_ServiceDesc.Streams[1], ArcadeDbService_InsertStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InsertChunk, InsertSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArcadeDbService_InsertStreamClient = grpc.ClientStreamingClient[InsertChunk, InsertSummary]

func (c *arcadeDbServiceClient) InsertBidirectional(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InsertRequest, InsertResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArcadeDbService_ServiceDesc.Streams[2], ArcadeDbService_InsertBidirectional_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InsertRequest, InsertResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArcadeDbService_InsertBidirectionalClient = grpc.BidiStreamingClient[InsertRequest, InsertResponse]

func (c *arcadeDbServiceClient) BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginTransactionResponse)
	err := c.cc.Invoke(ctx, ArcadeDbService_BeginTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbServiceClient) CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*CommitTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitTransactionResponse)
	err := c.cc.Invoke(ctx, ArcadeDbService_CommitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbServiceClient) RollbackTransaction(ctx context.Context, in *RollbackTransactionRequest, opts ...grpc.CallOption) (*RollbackTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackTransactionResponse)
	err := c.cc.Invoke(ctx, ArcadeDbService_RollbackTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArcadeDbServiceServer is the server API for ArcadeDbService service.
// All implementations must embed UnimplementedArcadeDbServiceServer
// for forward compatibility.
type ArcadeDbServiceServer interface {
	// Streaming queries
	StreamQuery(*StreamQueryRequest, grpc.ServerStreamingServer[QueryResult]) error
	// Execute arbitrary command (INSERT/UPDATE/DDL/etc.)
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error)
	// Single-record helpers
	CreateRecord(context.Context, *CreateRecordRequest) (*CreateRecordResponse, error)
	UpdateRecord(context.Context, *UpdateRecordRequest) (*UpdateRecordResponse, error)
	LookupByRid(context.Context, *LookupByRidRequest) (*LookupByRidResponse, error)
	DeleteRecord(context.Context, *DeleteRecordRequest) (*DeleteRecordResponse, error)
	// Insert APIs (unary, client-streaming, and bidi)
	BulkInsert(context.Context, *BulkInsertRequest) (*InsertSummary, error)
	InsertStream(grpc.ClientStreamingServer[InsertChunk, InsertSummary]) error
	InsertBidirectional(grpc.BidiStreamingServer[InsertRequest, InsertResponse]) error
	// Transaction operations
	BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error)
	CommitTransaction(context.Context, *CommitTransactionRequest) (*CommitTransactionResponse, error)
	RollbackTransaction(context.Context, *RollbackTransactionRequest) (*RollbackTransactionResponse, error)
	mustEmbedUnimplementedArcadeDbServiceServer()
}

// UnimplementedArcadeDbServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArcadeDbServiceServer struct{}

func (UnimplementedArcadeDbServiceServer) StreamQuery(*StreamQueryRequest, grpc.ServerStreamingServer[QueryResult]) error {
	return status.Error(codes.Unimplemented, "method StreamQuery not implemented")
}
func (UnimplementedArcadeDbServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedArcadeDbServiceServer) ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedArcadeDbServiceServer) CreateRecord(context.Context, *CreateRecordRequest) (*CreateRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRecord not implemented")
}
func (UnimplementedArcadeDbServiceServer) UpdateRecord(context.Context, *UpdateRecordRequest) (*UpdateRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRecord not implemented")
}
func (UnimplementedArcadeDbServiceServer) LookupByRid(context.Context, *LookupByRidRequest) (*LookupByRidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupByRid not implemented")
}
func (UnimplementedArcadeDbServiceServer) DeleteRecord(context.Context, *DeleteRecordRequest) (*DeleteRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRecord not implemented")
}
func (UnimplementedArcadeDbServiceServer) BulkInsert(context.Context, *BulkInsertRequest) (*InsertSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkInsert not implemented")
}
func (UnimplementedArcadeDbServiceServer) InsertStream(grpc.ClientStreamingServer[InsertChunk, InsertSummary]) error {
	return status.Error(codes.Unimplemented, "method InsertStream not implemented")
}
func (UnimplementedArcadeDbServiceServer) InsertBidirectional(grpc.BidiStreamingServer[InsertRequest, InsertResponse]) error {
	return status.Error(codes.Unimplemented, "method InsertBidirectional not implemented")
}
func (UnimplementedArcadeDbServiceServer) BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginTransaction not implemented")
}
func (UnimplementedArcadeDbServiceServer) CommitTransaction(context.Context, *CommitTransactionRequest) (*CommitTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitTransaction not implemented")
}
func (UnimplementedArcadeDbServiceServer) RollbackTransaction(context.Context, *RollbackTransactionRequest) (*RollbackTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackTransaction not implemented")
}
func (UnimplementedArcadeDbServiceServer) mustEmbedUnimplementedArcadeDbServiceServer() {}
func (UnimplementedArcadeDbServiceServer) testEmbeddedByValue()                         {}

// UnsafeArcadeDbServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArcadeDbServiceServer will
// result in compilation errors.
type UnsafeArcadeDbServiceServer interface {
	mustEmbedUnimplementedArcadeDbServiceServer()
}

func RegisterArcadeDbServiceServer(s grpc.ServiceRegistrar, srv ArcadeDbServiceServer) {
	// If the following call panics, it indicates UnimplementedArcadeDbServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArcadeDbService_ServiceDesc, srv)
}

func _ArcadeDbService_StreamQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ArcadeDbServiceServer).StreamQuery(m, &grpc.GenericServerStream[StreamQueryRequest, QueryResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArcadeDbService_StreamQueryServer = grpc.ServerStreamingServer[QueryResult]

func _ArcadeDbService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbServiceServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbService_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbServiceServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbService_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbServiceServer).ExecuteQuery(ctx, req.(*ExecuteQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbService_CreateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbServiceServer).CreateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbService_CreateRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbServiceServer).CreateRecord(ctx, req.(*CreateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbService_UpdateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbServiceServer).UpdateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbService_UpdateRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbServiceServer).UpdateRecord(ctx, req.(*UpdateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbService_LookupByRid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupByRidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbServiceServer).LookupByRid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbService_LookupByRid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbServiceServer).LookupByRid(ctx, req.(*LookupByRidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbService_DeleteRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbServiceServer).DeleteRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbService_DeleteRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbServiceServer).DeleteRecord(ctx, req.(*DeleteRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbService_BulkInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbServiceServer).BulkInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbService_BulkInsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbServiceServer).BulkInsert(ctx, req.(*BulkInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbService_InsertStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArcadeDbServiceServer).InsertStream(&grpc.GenericServerStream[InsertChunk, InsertSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArcadeDbService_InsertStreamServer = grpc.ClientStreamingServer[InsertChunk, InsertSummary]

func _ArcadeDbService_InsertBidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArcadeDbServiceServer).InsertBidirectional(&grpc.GenericServerStream[InsertRequest, InsertResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArcadeDbService_InsertBidirectionalServer = grpc.BidiStreamingServer[InsertRequest, InsertResponse]

func _ArcadeDbService_BeginTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbServiceServer).BeginTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbService_BeginTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbServiceServer).BeginTransaction(ctx, req.(*BeginTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbService_CommitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbServiceServer).CommitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbService_CommitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbServiceServer).CommitTransaction(ctx, req.(*CommitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbService_RollbackTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbServiceServer).RollbackTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbService_RollbackTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbServiceServer).RollbackTransaction(ctx, req.(*RollbackTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArcadeDbService_ServiceDesc is the grpc.ServiceDesc for ArcadeDbService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArcadeDbService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.arcadedb.grpc.ArcadeDbService",
	HandlerType: (*ArcadeDbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _ArcadeDbService_ExecuteCommand_Handler,
		},
		{
			MethodName: "ExecuteQuery",
			Handler:    _ArcadeDbService_ExecuteQuery_Handler,
		},
		{
			MethodName: "CreateRecord",
			Handler:    _ArcadeDbService_CreateRecord_Handler,
		},
		{
			MethodName: "UpdateRecord",
			Handler:    _ArcadeDbService_UpdateRecord_Handler,
		},
		{
			MethodName: "LookupByRid",
			Handler:    _ArcadeDbService_LookupByRid_Handler,
		},
		{
			MethodName: "DeleteRecord",
			Handler:    _ArcadeDbService_DeleteRecord_Handler,
		},
		{
			MethodName: "BulkInsert",
			Handler:    _ArcadeDbService_BulkInsert_Handler,
		},
		{
			MethodName: "BeginTransaction",
			Handler:    _ArcadeDbService_BeginTransaction_Handler,
		},
		{
			MethodName: "CommitTransaction",
			Handler:    _ArcadeDbService_CommitTransaction_Handler,
		},
		{
			MethodName: "RollbackTransaction",
			Handler:    _ArcadeDbService_RollbackTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamQuery",
			Handler:       _ArcadeDbService_StreamQuery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InsertStream",
			Handler:       _ArcadeDbService_InsertStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "InsertBidirectional",
			Handler:       _ArcadeDbService_InsertBidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "arcadedb-server.proto",
}

const (
	ArcadeDbAdminService_Ping_FullMethodName            = "/com.arcadedb.grpc.ArcadeDbAdminService/Ping"
	ArcadeDbAdminService_GetServerInfo_FullMethodName   = "/com.arcadedb.grpc.ArcadeDbAdminService/GetServerInfo"
	ArcadeDbAdminService_ListDatabases_FullMethodName   = "/com.arcadedb.grpc.ArcadeDbAdminService/ListDatabases"
	ArcadeDbAdminService_ExistsDatabase_FullMethodName  = "/com.arcadedb.grpc.ArcadeDbAdminService/ExistsDatabase"
	ArcadeDbAdminService_CreateDatabase_FullMethodName  = "/com.arcadedb.grpc.ArcadeDbAdminService/CreateDatabase"
	ArcadeDbAdminService_DropDatabase_FullMethodName    = "/com.arcadedb.grpc.ArcadeDbAdminService/DropDatabase"
	ArcadeDbAdminService_GetDatabaseInfo_FullMethodName = "/com.arcadedb.grpc.ArcadeDbAdminService/GetDatabaseInfo"
	ArcadeDbAdminService_CreateUser_FullMethodName      = "/com.arcadedb.grpc.ArcadeDbAdminService/CreateUser"
	ArcadeDbAdminService_DeleteUser_FullMethodName      = "/com.arcadedb.grpc.ArcadeDbAdminService/DeleteUser"
)

// ArcadeDbAdminServiceClient is the client API for ArcadeDbAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArcadeDbAdminServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
	ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error)
	ExistsDatabase(ctx context.Context, in *ExistsDatabaseRequest, opts ...grpc.CallOption) (*ExistsDatabaseResponse, error)
	CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error)
	DropDatabase(ctx context.Context, in *DropDatabaseRequest, opts ...grpc.CallOption) (*DropDatabaseResponse, error)
	GetDatabaseInfo(ctx context.Context, in *GetDatabaseInfoRequest, opts ...grpc.CallOption) (*GetDatabaseInfoResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type arcadeDbAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArcadeDbAdminServiceClient(cc grpc.ClientConnInterface) ArcadeDbAdminServiceClient {
	return &arcadeDbAdminServiceClient{cc}
}

func (c *arcadeDbAdminServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, ArcadeDbAdminService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbAdminServiceClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, ArcadeDbAdminService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbAdminServiceClient) ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatabasesResponse)
	err := c.cc.Invoke(ctx, ArcadeDbAdminService_ListDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbAdminServiceClient) ExistsDatabase(ctx context.Context, in *ExistsDatabaseRequest, opts ...grpc.CallOption) (*ExistsDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsDatabaseResponse)
	err := c.cc.Invoke(ctx, ArcadeDbAdminService_ExistsDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbAdminServiceClient) CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDatabaseResponse)
	err := c.cc.Invoke(ctx, ArcadeDbAdminService_CreateDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbAdminServiceClient) DropDatabase(ctx context.Context, in *DropDatabaseRequest, opts ...grpc.CallOption) (*DropDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropDatabaseResponse)
	err := c.cc.Invoke(ctx, ArcadeDbAdminService_DropDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbAdminServiceClient) GetDatabaseInfo(ctx context.Context, in *GetDatabaseInfoRequest, opts ...grpc.CallOption) (*GetDatabaseInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatabaseInfoResponse)
	err := c.cc.Invoke(ctx, ArcadeDbAdminService_GetDatabaseInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbAdminServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, ArcadeDbAdminService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arcadeDbAdminServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, ArcadeDbAdminService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArcadeDbAdminServiceServer is the server API for ArcadeDbAdminService service.
// All implementations must embed UnimplementedArcadeDbAdminServiceServer
// for forward compatibility.
type ArcadeDbAdminServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error)
	ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error)
	ExistsDatabase(context.Context, *ExistsDatabaseRequest) (*ExistsDatabaseResponse, error)
	CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error)
	DropDatabase(context.Context, *DropDatabaseRequest) (*DropDatabaseResponse, error)
	GetDatabaseInfo(context.Context, *GetDatabaseInfoRequest) (*GetDatabaseInfoResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	mustEmbedUnimplementedArcadeDbAdminServiceServer()
}

// UnimplementedArcadeDbAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArcadeDbAdminServiceServer struct{}

func (UnimplementedArcadeDbAdminServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedArcadeDbAdminServiceServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedArcadeDbAdminServiceServer) ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatabases not implemented")
}
func (UnimplementedArcadeDbAdminServiceServer) ExistsDatabase(context.Context, *ExistsDatabaseRequest) (*ExistsDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExistsDatabase not implemented")
}
func (UnimplementedArcadeDbAdminServiceServer) CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDatabase not implemented")
}
func (UnimplementedArcadeDbAdminServiceServer) DropDatabase(context.Context, *DropDatabaseRequest) (*DropDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropDatabase not implemented")
}
func (UnimplementedArcadeDbAdminServiceServer) GetDatabaseInfo(context.Context, *GetDatabaseInfoRequest) (*GetDatabaseInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDatabaseInfo not implemented")
}
func (UnimplementedArcadeDbAdminServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedArcadeDbAdminServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedArcadeDbAdminServiceServer) mustEmbedUnimplementedArcadeDbAdminServiceServer() {}
func (UnimplementedArcadeDbAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeArcadeDbAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArcadeDbAdminServiceServer will
// result in compilation errors.
type UnsafeArcadeDbAdminServiceServer interface {
	mustEmbedUnimplementedArcadeDbAdminServiceServer()
}

func RegisterArcadeDbAdminServiceServer(s grpc.ServiceRegistrar, srv ArcadeDbAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedArcadeDbAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArcadeDbAdminService_ServiceDesc, srv)
}

func _ArcadeDbAdminService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbAdminServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbAdminService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbAdminServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbAdminService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbAdminServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbAdminService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbAdminServiceServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbAdminService_ListDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbAdminServiceServer).ListDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbAdminService_ListDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbAdminServiceServer).ListDatabases(ctx, req.(*ListDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbAdminService_ExistsDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbAdminServiceServer).ExistsDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbAdminService_ExistsDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbAdminServiceServer).ExistsDatabase(ctx, req.(*ExistsDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbAdminService_CreateDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbAdminServiceServer).CreateDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbAdminService_CreateDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbAdminServiceServer).CreateDatabase(ctx, req.(*CreateDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbAdminService_DropDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbAdminServiceServer).DropDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbAdminService_DropDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbAdminServiceServer).DropDatabase(ctx, req.(*DropDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbAdminService_GetDatabaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbAdminServiceServer).GetDatabaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbAdminService_GetDatabaseInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbAdminServiceServer).GetDatabaseInfo(ctx, req.(*GetDatabaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbAdminService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbAdminServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbAdminService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbAdminServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArcadeDbAdminService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcadeDbAdminServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArcadeDbAdminService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcadeDbAdminServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArcadeDbAdminService_ServiceDesc is the grpc.ServiceDesc for ArcadeDbAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArcadeDbAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.arcadedb.grpc.ArcadeDbAdminService",
	HandlerType: (*ArcadeDbAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ArcadeDbAdminService_Ping_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _ArcadeDbAdminService_GetServerInfo_Handler,
		},
		{
			MethodName: "ListDatabases",
			Handler:    _ArcadeDbAdminService_ListDatabases_Handler,
		},
		{
			MethodName: "ExistsDatabase",
			Handler:    _ArcadeDbAdminService_ExistsDatabase_Handler,
		},
		{
			MethodName: "CreateDatabase",
			Handler:    _ArcadeDbAdminService_CreateDatabase_Handler,
		},
		{
			MethodName: "DropDatabase",
			Handler:    _ArcadeDbAdminService_DropDatabase_Handler,
		},
		{
			MethodName: "GetDatabaseInfo",
			Handler:    _ArcadeDbAdminService_GetDatabaseInfo_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _ArcadeDbAdminService_CreateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _ArcadeDbAdminService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arcadedb-server.proto",
}
