// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file bibliophage/v1alpha2/document.proto (package bibliophage.v1alpha2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteDocumentRequest, DeleteDocumentResponse, GetDocumentRequest, GetDocumentResponse, SearchDocumentsRequest, SearchDocumentsResponse, StoreDocumentRequest, StoreDocumentResponse, UpdateDocumentRequest, UpdateDocumentResponse } from "./document_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definitions - the API endpoints
 *
 * @generated from service bibliophage.v1alpha2.DocumentService
 */
export const DocumentService = {
  typeName: "bibliophage.v1alpha2.DocumentService",
  methods: {
    /**
     * @generated from rpc bibliophage.v1alpha2.DocumentService.StoreDocument
     */
    storeDocument: {
      name: "StoreDocument",
      I: StoreDocumentRequest,
      O: StoreDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha2.DocumentService.GetDocument
     */
    getDocument: {
      name: "GetDocument",
      I: GetDocumentRequest,
      O: GetDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha2.DocumentService.UpdateDocument
     */
    updateDocument: {
      name: "UpdateDocument",
      I: UpdateDocumentRequest,
      O: UpdateDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha2.DocumentService.SearchDocuments
     */
    searchDocuments: {
      name: "SearchDocuments",
      I: SearchDocumentsRequest,
      O: SearchDocumentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha2.DocumentService.DeleteDocument
     */
    deleteDocument: {
      name: "DeleteDocument",
      I: DeleteDocumentRequest,
      O: DeleteDocumentResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

