// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file bibliophage/v1alpha2/pdf.proto (package bibliophage.v1alpha2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetPdfRequest, GetPdfResponse, LoadPdfRequest, LoadPdfResponse, SearchPdfsRequest, SearchPdfsResponse } from "./pdf_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definitions - the API endpoints
 *
 * @generated from service bibliophage.v1alpha2.PdfService
 */
export const PdfService = {
  typeName: "bibliophage.v1alpha2.PdfService",
  methods: {
    /**
     * @generated from rpc bibliophage.v1alpha2.PdfService.LoadPdf
     */
    loadPdf: {
      name: "LoadPdf",
      I: LoadPdfRequest,
      O: LoadPdfResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha2.PdfService.SearchPdfs
     */
    searchPdfs: {
      name: "SearchPdfs",
      I: SearchPdfsRequest,
      O: SearchPdfsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bibliophage.v1alpha2.PdfService.GetPdf
     */
    getPdf: {
      name: "GetPdf",
      I: GetPdfRequest,
      O: GetPdfResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

